import { DetailedTopicContent } from '../../types/neet';

export const chemBasicReactionMechanismsDetails: DetailedTopicContent = {
  topicId: 'chem-basic-reaction-mechanisms',
  topicName: 'Basic Organic Reaction Mechanisms',
  subject: 'Chemistry',
  class: 'Class 11',
  classification: 'Organic Chemistry (Class 11)',
  chapter: 'Organic Chemistry: Some Basic Principles & Techniques',

  whatIsThisTopic:
    'Organic chemical reactions take place through step-by-step molecular processes called reaction mechanisms. A mechanism describes the exact sequence of elementary steps involved in a reaction, including the breaking of existing covalent bonds, the movement of electron pairs or single electrons, the transient formation of reactive intermediates (carbocations, carbanions, free radicals), and the reorganization of bonds to yield final products. Understanding mechanisms allows NEET aspirants to predict reaction pathways, product distribution, stereochemistry, and intermediate stability without memorizing hundreds of individual reactions.',

  basicIdea: [
    '1. Bond Cleavage Dynamics: Covalent bonds break in two distinct ways: Homolytic Fission (symmetrical cleavage producing neutral Free Radicals with unpaired electrons, favoured by UV light, high temperature, peroxides, and non-polar conditions) and Heterolytic Fission (unsymmetrical cleavage producing charged Carbocations and Carbanions, favoured by polar solvents).',
    '2. Attacking Reagents & Electron Movement: Reagents seeking electron density are Electrophiles (electron-pair acceptors / Lewis acids), whereas reagents supplying electron density are Nucleophiles (electron-pair donors / Lewis bases). Curved double-headed arrows (↷) show movement of electron PAIRS, while half-headed fishhook arrows (rightharpoonup) show movement of SINGLE electrons.',
    '3. Reaction Types & Mechanism Pathways: Organic transformations fall into four fundamental mechanisms: Substitution (Nucleophilic SN1/SN2, Electrophilic SE, Free Radical), Addition (Electrophilic, Nucleophilic, Free Radical), Elimination (E1, E2, E1cB), and Rearrangement (1,2-hydride or 1,2-methyl shifts driven by carbocation stability).'
  ],

  importantTerms: [
    {
      term: 'Homolytic Cleavage (Homolysis)',
      definition: 'Symmetrical breaking of a covalent bond where each bonded atom retains one electron from the shared electron pair, producing two neutral free radicals.',
      neetNote: 'Favoured by UV light (hν), peroxides (R-O-O-R), high temperatures (>500°C), and non-polar gas-phase conditions (HELP rule: Heat, Electricity, Light, Peroxides).'
    },
    {
      term: 'Heterolytic Cleavage (Heterolysis)',
      definition: 'Unsymmetrical breaking of a covalent bond where both bonding electrons are retained by the more electronegative atom, forming a cation and an anion.',
      neetNote: 'Favoured by polar protic solvents (H₂O, EtOH) and produces carbocations (R⁺) or carbanions (R⁻).'
    },
    {
      term: 'Free Radical (R•)',
      definition: 'A neutral chemical species carrying an unpaired valence electron generated by homolytic bond fission.',
      neetNote: 'Paramagnetic, highly reactive, sp² hybridized (planar), possessing 7 valence electrons.'
    },
    {
      term: 'Carbocation (R⁺)',
      definition: 'A positively charged organic intermediate containing a carbon atom with 6 valence electrons and a vacant 2p orbital.',
      neetNote: 'sp² hybridized, planar (120° bond angles), diamagnetic, electron-deficient (Lewis acid).'
    },
    {
      term: 'Carbanion (R⁻)',
      definition: 'A negatively charged organic intermediate containing a carbon atom with 8 valence electrons and an unshared lone pair.',
      neetNote: 'sp³ hybridized, trigonal pyramidal geometry, electron-rich (Lewis base / nucleophile).'
    },
    {
      term: 'Electrophile (E⁺)',
      definition: 'An electron-deficient species (positive ion or neutral molecule with an incomplete octet or vacant d/p orbital) that accepts an electron pair.',
      neetNote: 'Examples: Positive (H⁺, NO₂⁺, Cl⁺, R⁺) and Neutral (BF₃, AlCl₃, FeCl₃, SO₃, :CH₂ carbene).'
    },
    {
      term: 'Nucleophile (Nu⁻)',
      definition: 'An electron-rich species (negative ion or neutral molecule with lone pairs or π-bonds) capable of donating an electron pair.',
      neetNote: 'Examples: Negative (OH⁻, CN⁻, RO⁻, X⁻) and Neutral (H₂O, NH₃, R-OH, R-NH₂).'
    },
    {
      term: 'Ambident Nucleophile',
      definition: 'A nucleophile that possesses two nucleophilic centers capable of donating an electron pair from two different atoms.',
      neetNote: 'High NEET Yield: CN⁻ (attacks via C to give Cyanide or via N to give Isocyanide) and NO₂⁻ (attacks via O to give Nitrite or via N to give Nitro compound).'
    },
    {
      term: 'Ambiphile',
      definition: 'A chemical species possessing both an electron-deficient site and an unshared lone pair, allowing it to act as both an electrophile and a nucleophile.',
      neetNote: 'Examples: Water (H₂O), Alcohol (R-OH), Aldehydes (R-CHO).'
    },
    {
      term: 'Curved Arrow Notation (↷)',
      definition: 'A symbolic notation showing the flow of an electron PAIR from an electron source (lone pair or bond) to an electron sink (atom or bond).',
      neetNote: 'The tail starts at the electron source; the head points to the destination. Never draw an arrow starting from a positive charge!'
    },
    {
      term: 'Fishhook Arrow Notation (rightharpoonup)',
      definition: 'A half-headed curved arrow indicating the movement of a SINGLE electron during homolytic cleavage or free radical steps.',
      neetNote: 'Used exclusively in radical mechanisms.'
    },
    {
      term: 'Substitution Reaction',
      definition: 'A reaction in which an atom or group attached to a carbon atom is replaced by another atom or group without altering the overall saturation.',
      neetNote: 'Types: Nucleophilic (SN1, SN2), Electrophilic (SEAr in Benzene), Free Radical (Halogenation of alkanes).'
    },
    {
      term: 'Addition Reaction',
      definition: 'A reaction in which unsaturated molecules (alkenes, alkynes, carbonyls) combine with reagents to yield saturated products with no atoms eliminated.',
      neetNote: 'Types: Electrophilic Addition (alkenes + HX), Nucleophilic Addition (carbonyls + HCN), Free Radical Addition (Anti-Markovnikov HBr + Peroxide).'
    },
    {
      term: 'Elimination Reaction',
      definition: 'A reaction involving the loss of two atoms or groups from adjacent carbons, resulting in the formation of a π-bond (alkenes or alkynes).',
      neetNote: 'Types: E1 (via carbocation), E2 (concerted, transition state), E1cB (via carbanion).'
    },
    {
      term: 'Carbocation Rearrangement (1,2-Shift)',
      definition: 'The spontaneous migration of a hydride (:H⁻) or alkyl/aryl group from an adjacent carbon to a positively charged carbon to yield a more stable carbocation.',
      neetNote: 'Driven by thermodynamics (1° → 2° → 3° or allylic/benzylic). Occurs in SN1 and E1 reactions.'
    }
  ],

  conceptExplanation: [
    {
      heading: '1. Homolytic vs Heterolytic Bond Cleavage',
      paragraphs: [
        'Covalent bonds consist of shared electron pairs between atoms. The method of bond cleavage governs the nature of the chemical species formed and determines the entire reaction mechanism pathway.',
        '• Homolytic Cleavage (Homolysis): Symmetrical bond fission where the shared pair of electrons is divided equally between the two cleavage fragments. Each fragment retains ONE unpaired electron, producing neutral, highly energetic Free Radicals (A• and B•). Homolysis requires high energy inputs and is favoured by heat (Δ), ultraviolet light (hν), peroxide catalysts (R-O-O-R), and non-polar gas or liquid phases.',
        '• Heterolytic Cleavage (Heterolysis): Unsymmetrical bond fission where the more electronegative atom retains BOTH bonding electrons. This leaves one fragment positively charged (electron-deficient cation) and the other negatively charged (electron-rich anion). Heterolysis is favoured by polar protic solvents (e.g., H₂O, CH₃OH) which stabilize the resulting ions through solvation.'
      ],
      visuals: [
        {
          caption: 'Direct Visual Comparison: Homolytic vs Heterolytic Bond Fission showing electron movements, arrow types, and resulting species.',
          guide: 'Fishhook arrows (single electron) are used in homolysis to form free radicals. Curved arrows (electron pair) are used in heterolysis to form carbocations and carbanions.',
          svgContent: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 280" class="w-full h-auto rounded-xl bg-slate-50 dark:bg-slate-900 font-sans border border-slate-200 dark:border-slate-800">
            <rect width="800" height="280" rx="16" fill="#f8fafc" class="dark:fill-slate-900"/>
            <text x="400" y="28" text-anchor="middle" class="fill-slate-900 dark:fill-slate-100 font-black text-sm">Homolytic vs Heterolytic Bond Cleavage Mechanisms</text>
            
            <!-- LEFT BOX: HOMOLYTIC CLEAVAGE -->
            <g transform="translate(30, 48)">
              <rect width="355" height="210" rx="14" class="fill-white dark:fill-slate-950 stroke-amber-300 dark:stroke-amber-700" stroke-width="1.5"/>
              <text x="177" y="26" text-anchor="middle" class="fill-amber-700 dark:fill-amber-400 font-bold text-xs">Homolytic Cleavage (Homolysis)</text>
              
              <!-- Reaction Equation -->
              <text x="177" y="65" text-anchor="middle" class="fill-slate-900 dark:fill-slate-100 font-mono font-bold text-sm">A ─ B   𝛥 / h𝜈   ──►   A•  +  B•</text>
              
              <!-- Fishhook representation -->
              <g transform="translate(75, 80)">
                <text x="50" y="30" text-anchor="middle" class="fill-amber-600 dark:fill-amber-400 font-mono text-xs">Fishhook Arrows (rightharpoonup)</text>
                <path d="M 60,40 C 40,20 20,20 10,35" fill="none" stroke="#d97706" stroke-width="2"/>
                <polygon points="10,35 16,30 18,37" fill="#d97706"/>
                <path d="M 80,40 C 100,20 120,20 130,35" fill="none" stroke="#d97706" stroke-width="2"/>
                <polygon points="130,35 124,30 122,37" fill="#d97706"/>
              </g>
              
              <!-- Key Characteristics -->
              <rect x="15" y="135" width="325" height="60" rx="8" class="fill-amber-50 dark:fill-amber-950/60 stroke-amber-200 dark:stroke-amber-800" stroke-width="1"/>
              <text x="25" y="153" class="fill-amber-900 dark:fill-amber-200 text-[11px] font-semibold">• Symmetrical electron division (1 e⁻ to each atom)</text>
              <text x="25" y="169" class="fill-amber-900 dark:fill-amber-200 text-[11px] font-semibold">• Products: Neutral Free Radicals (unpaired e⁻)</text>
              <text x="25" y="185" class="fill-amber-900 dark:fill-amber-200 text-[11px] font-semibold">• Favoured by: UV Light (h𝜈), Heat (𝛥), Peroxides, Gas phase</text>
            </g>
            
            <!-- RIGHT BOX: HETEROLYTIC CLEAVAGE -->
            <g transform="translate(415, 48)">
              <rect width="355" height="210" rx="14" class="fill-white dark:fill-slate-950 stroke-indigo-300 dark:stroke-indigo-700" stroke-width="1.5"/>
              <text x="177" y="26" text-anchor="middle" class="fill-indigo-700 dark:fill-indigo-400 font-bold text-xs">Heterolytic Cleavage (Heterolysis)</text>
              
              <!-- Reaction Equation -->
              <text x="177" y="65" text-anchor="middle" class="fill-slate-900 dark:fill-slate-100 font-mono font-bold text-sm">A ─ B   Polar Solvent   ──►   A⁺  +  :B⁻</text>
              
              <!-- Curved arrow representation -->
              <g transform="translate(75, 80)">
                <text x="100" y="30" text-anchor="middle" class="fill-indigo-600 dark:fill-indigo-400 font-mono text-xs">Curved Arrow (2 e⁻ transfer)</text>
                <path d="M 50,40 C 70,10 110,10 130,35" fill="none" stroke="#4f46e5" stroke-width="2.5"/>
                <polygon points="130,35 122,30 123,39" fill="#4f46e5"/>
              </g>
              
              <!-- Key Characteristics -->
              <rect x="15" y="135" width="325" height="60" rx="8" class="fill-indigo-50 dark:fill-indigo-950/60 stroke-indigo-200 dark:stroke-indigo-800" stroke-width="1"/>
              <text x="25" y="153" class="fill-indigo-900 dark:fill-indigo-200 text-[11px] font-semibold">• Unsymmetrical division (Both e⁻ to electronegative atom)</text>
              <text x="25" y="169" class="fill-indigo-900 dark:fill-indigo-200 text-[11px] font-semibold">• Products: Charged Ions (Carbocation R⁺ + Carbanion R⁻)</text>
              <text x="25" y="185" class="fill-indigo-900 dark:fill-indigo-200 text-[11px] font-semibold">• Favoured by: Polar Protic Solvents (H₂O, EtOH)</text>
            </g>
          </svg>`
        }
      ],
      importantPoints: [
        '🎯 NEET Memory Trick: HELP Rule for Homolysis → H (Heat), E (Electricity), L (Light/hν), P (Peroxides). Any reaction with these conditions proceeds via FREE RADICALS!',
        'Solvent Effect: Polar protic solvents like H₂O lower the activation energy of heterolytic cleavage by solvating both cations and anions through ion-dipole and hydrogen bonding interactions.'
      ]
    },
    {
      heading: '2. Electrophiles vs Nucleophiles (Classification & Identification)',
      paragraphs: [
        'Attacking reagents in organic chemistry are classified based on whether they seek electron density or supply electron density during reaction steps.',
        '• Electrophiles (E⁺ / "Electron-Loving"): Electron-deficient species that accept an electron pair from a nucleophile to form a covalent bond (Lewis Acids). Electrophiles possess either a positive formal charge or a neutral atom with an incomplete octet or vacant low-energy orbital.',
        '• Positively Charged Electrophiles: H⁺, H₃O⁺, NO₂⁺ (Nitronium ion), Cl⁺, Br⁺, I⁺, R⁺ (Carbocations), R-C⁺=O (Acylium ion).',
        '• Neutral Electrophiles (High NEET Yield!): BF₃, AlCl₃, FeCl₃, ZnCl₂ (Lewis acids with incomplete octet), SO₃ (sulfur trioxide in sulfonation), CO₂ (carbon dioxide in Grignard reaction), :CH₂ / :CCl₂ (Carbenes in Reimer-Tiemann reaction).',
        '• Nucleophiles (Nu⁻ / "Nucleus-Loving"): Electron-rich species that donate an electron pair to an electron-deficient atom to form a covalent bond (Lewis Bases). Nucleophiles possess either a negative formal charge or neutral atoms carrying unshared lone pairs.',
        '• Negatively Charged Nucleophiles: OH⁻, RO⁻, HS⁻, CN⁻, I⁻, Br⁻, Cl⁻, F⁻, R⁻ (Carbanions from RMgX Grignard reagents), R-COO⁻.',
        '• Neutral Nucleophiles: H₂O (lone pair on Oxygen), NH₃ (lone pair on Nitrogen), R-OH, R-NH₂, R-SH.',
        '• Ambident Nucleophiles: Nucleophiles possessing TWO potential electron-donating atoms. Cyanide (CN⁻: attacks via C to form Nitrile, or via N to form Isocyanide) and Nitrite (NO₂⁻: attacks via N to form Nitroalkane, or via O to form Alkyl Nitrite).'
      ],
      visuals: [
        {
          caption: 'Visual Classification of Electrophiles and Nucleophiles with attack mechanisms and electron donor/acceptor roles.',
          guide: 'Electrophiles accept an electron pair into a vacant orbital. Nucleophiles donate an electron pair from a lone pair or negative charge.',
          svgContent: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 290" class="w-full h-auto rounded-xl bg-slate-50 dark:bg-slate-900 font-sans border border-slate-200 dark:border-slate-800">
            <rect width="800" height="290" rx="16" fill="#f8fafc" class="dark:fill-slate-900"/>
            <text x="400" y="28" text-anchor="middle" class="fill-slate-900 dark:fill-slate-100 font-black text-sm">Classification & Mechanisms of Reagents (Electrophiles vs Nucleophiles)</text>
            
            <!-- ELECTROPHILES COLUMN -->
            <g transform="translate(30, 48)">
              <rect width="355" height="220" rx="12" class="fill-white dark:fill-slate-950 stroke-blue-300 dark:stroke-blue-700" stroke-width="1.5"/>
              <text x="177" y="25" text-anchor="middle" class="fill-blue-700 dark:fill-blue-400 font-bold text-xs">Electrophiles (E⁺) ── Electron Acceptors (Lewis Acids)</text>
              
              <rect x="15" y="40" width="325" height="75" rx="8" class="fill-blue-50 dark:fill-blue-950/60 border border-blue-200 dark:border-blue-800"/>
              <text x="25" y="58" class="fill-blue-900 dark:fill-blue-200 text-[11px] font-bold">Positively Charged:</text>
              <text x="25" y="74" class="fill-slate-800 dark:fill-slate-200 font-mono text-[11px]">H⁺, NO₂⁺, Cl⁺, Br⁺, R⁺ (Carbocations), RCO⁺</text>
              <text x="25" y="94" class="fill-blue-900 dark:fill-blue-200 text-[11px] font-bold">Neutral (Incomplete Octet / Empty Orbital):</text>
              <text x="25" y="108" class="fill-slate-800 dark:fill-slate-200 font-mono text-[11px]">BF₃, AlCl₃, FeCl₃, SO₃, CO₂, :CH₂ (Carbene)</text>
              
              <g transform="translate(15, 125)">
                <rect width="325" height="80" rx="8" class="fill-slate-100 dark:fill-slate-900 border border-slate-300 dark:border-slate-700"/>
                <text x="162" y="22" text-anchor="middle" class="fill-blue-800 dark:fill-blue-300 font-bold text-[11px]">Mechanism of Attack:</text>
                <text x="162" y="45" text-anchor="middle" class="fill-slate-900 dark:fill-slate-100 font-mono font-bold text-xs">Nu:⁻  +  E⁺   ──►   Nu ── E</text>
                <path d="M 120,40 Q 160,20 200,40" fill="none" stroke="#2563eb" stroke-width="2.5"/>
                <polygon points="200,40 192,35 193,44" fill="#2563eb"/>
                <text x="162" y="68" text-anchor="middle" class="fill-slate-500 dark:fill-slate-400 text-[10px]">Nucleophile attacks electron-deficient Electrophile</text>
              </g>
            </g>
            
            <!-- NUCLEOPHILES COLUMN -->
            <g transform="translate(415, 48)">
              <rect width="355" height="220" rx="12" class="fill-white dark:fill-slate-950 stroke-emerald-300 dark:stroke-emerald-700" stroke-width="1.5"/>
              <text x="177" y="25" text-anchor="middle" class="fill-emerald-700 dark:fill-emerald-400 font-bold text-xs">Nucleophiles (Nu⁻) ── Electron Donors (Lewis Bases)</text>
              
              <rect x="15" y="40" width="325" height="75" rx="8" class="fill-emerald-50 dark:fill-emerald-950/60 border border-emerald-200 dark:border-emerald-800"/>
              <text x="25" y="58" class="fill-emerald-900 dark:fill-emerald-200 text-[11px] font-bold">Negatively Charged:</text>
              <text x="25" y="74" class="fill-slate-800 dark:fill-slate-200 font-mono text-[11px]">OH⁻, RO⁻, CN⁻, I⁻, Br⁻, Cl⁻, F⁻, R⁻ (Grignard)</text>
              <text x="25" y="94" class="fill-emerald-900 dark:fill-emerald-200 text-[11px] font-bold">Neutral (Unshared Lone Pairs):</text>
              <text x="25" y="108" class="fill-slate-800 dark:fill-slate-200 font-mono text-[11px]">H₂O, :NH₃, R-OH, R-NH₂, R-SH</text>
              
              <g transform="translate(15, 125)">
                <rect width="325" height="80" rx="8" class="fill-slate-100 dark:fill-slate-900 border border-slate-300 dark:border-slate-700"/>
                <text x="162" y="22" text-anchor="middle" class="fill-emerald-800 dark:fill-emerald-300 font-bold text-[11px]">Ambident Nucleophiles (Two Attack Sites):</text>
                <text x="162" y="45" text-anchor="middle" class="fill-slate-900 dark:fill-slate-100 font-mono font-bold text-xs">:C ≡ N:⁻   (C-attack → R-CN | N-attack → R-NC)</text>
                <text x="162" y="68" text-anchor="middle" class="fill-emerald-700 dark:fill-emerald-400 font-bold text-[10px]">AgCN yields Isocyanide (R-NC); KCN yields Cyanide (R-CN)</text>
              </g>
            </g>
          </svg>`
        }
      ],
      importantPoints: [
        '🎯 NEET NCERT Exception: AgCN vs KCN with Alkyl Halides! KCN is ionic, yielding CN⁻ which attacks via Carbon to form Alkyl Cyanide (R-CN). AgCN is covalent, forcing Nitrogen lone pair attack to form Alkyl Isocyanide (R-NC). Extremely high yield NEET question!',
        'Neutral Electrophiles Trap: Students often fail to recognize BF₃, AlCl₃, and FeCl₃ as electrophiles because they lack a positive charge. They are powerful electrophiles due to vacant p-orbitals (6 valence electrons).'
      ]
    },
    {
      heading: '3. Reaction Intermediates (Carbocations, Carbanions, Free Radicals)',
      paragraphs: [
        'Reaction intermediates are short-lived, highly reactive species generated during multi-step organic mechanisms. Their structure, hybridization, geometry, and relative stability dictate the speed and product outcome of organic reactions.',
        '1. Carbocations (R⁺): Positively charged carbon with 6 valence electrons (3 bonding pairs, 0 lone pairs). Hybridization is sp², giving trigonal planar geometry with a vacant 2p orbital perpendicular to the molecular plane. Bond angle is 120°.',
        '• Stability Order: 3° > 2° > 1° > CH₃⁺ (due to +I effect and hyperconjugation from α-hydrogens).',
        '• Resonance Stabilized Carbocations: Tropylium C₇H₇⁺ > Triphenylmethyl (Ph₃C⁺) > Diphenylmethyl (Ph₂CH⁺) > Benzyl (PhCH₂⁺) ≈ Allyl (CH₂=CH-CH₂⁺) > 3° Alkyl > 2° Alkyl > 1° Alkyl > CH₃⁺ > Vinyl (CH₂=CH⁺) > Phenyl (C₆H₅⁺).',
        '2. Carbanions (R⁻): Negatively charged carbon carrying 8 valence electrons (3 bonding pairs + 1 unshared lone pair). Hybridization is sp³, giving trigonal pyramidal geometry (similar to ammonia NH₃).',
        '• Stability Order: CH₃⁻ > 1° > 2° > 3° (Alkyl groups exert +I effect, pumping electron density into an already electron-rich carbanion, thereby destabilizing it).',
        '• Hybridization State Effect on Carbanions: HC≡C⁻ (sp, 50% s-character) > CH₂=CH⁻ (sp², 33.3% s-character) > CH₃-CH₂⁻ (sp³, 25% s-character). Higher % s-character holds negative charge closer to the nucleus, creating extraordinary stability!',
        '3. Free Radicals (R•): Neutral species with an unpaired electron, carrying 7 valence electrons (3 bonding pairs + 1 odd electron). Hybridization is sp², giving trigonal planar geometry with the odd electron residing in an unhybridized p-orbital.',
        '• Stability Order: 3° > 2° > 1° > CH₃• (stabilized by hyperconjugation from α-hydrogens and allylic/benzylic resonance).'
      ],
      visuals: [
        {
          caption: '3D Structural Architecture, Hybridization, Geometry, Orbital Layout, and Charge Distribution of Carbocations, Carbanions, and Free Radicals.',
          guide: 'Carbocation is sp² planar with empty p-orbital. Carbanion is sp³ pyramidal with lone pair. Free radical is sp² planar with unpaired electron in p-orbital.',
          svgContent: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 310" class="w-full h-auto rounded-xl bg-slate-50 dark:bg-slate-900 font-sans border border-slate-200 dark:border-slate-800">
            <rect width="800" height="310" rx="16" fill="#f8fafc" class="dark:fill-slate-900"/>
            <text x="400" y="28" text-anchor="middle" class="fill-slate-900 dark:fill-slate-100 font-black text-sm">Structure, Geometry & Orbital Diagrams of Key Reaction Intermediates</text>
            
            <!-- CARBOCATION CARD -->
            <g transform="translate(25, 48)">
              <rect width="235" height="245" rx="12" class="fill-white dark:fill-slate-950 stroke-blue-300 dark:stroke-blue-700" stroke-width="1.5"/>
              <text x="117" y="24" text-anchor="middle" class="fill-blue-700 dark:fill-blue-400 font-bold text-xs">Carbocation (R⁺)</text>
              
              <!-- Orbital drawing -->
              <g transform="translate(117, 85)">
                <!-- Empty 2p orbital lobes -->
                <path d="M 0,0 C -20,-35 20,-35 0,0 C -20,35 20,35 0,0" fill="none" stroke="#2563eb" stroke-width="2" stroke-dasharray="3,2"/>
                <text x="0" y="-40" text-anchor="middle" class="fill-blue-600 dark:fill-blue-400 font-bold text-[10px]">Empty 2p Orbital</text>
                <!-- Central Carbon -->
                <circle cx="0" cy="0" r="14" class="fill-blue-100 dark:fill-blue-900 stroke-blue-600 dark:stroke-blue-400" stroke-width="2"/>
                <text x="0" y="4" text-anchor="middle" class="fill-blue-900 dark:fill-blue-100 font-bold text-xs">C⁺</text>
                <!-- 3 bonds planar -->
                <line x1="-14" y1="0" x2="-45" y2="-10" stroke="#334155" stroke-width="2"/>
                <line x1="14" y1="0" x2="45" y2="-10" stroke="#334155" stroke-width="2"/>
                <line x1="0" y1="14" x2="0" y2="45" stroke="#334155" stroke-width="2"/>
              </g>
              
              <rect x="12" y="150" width="211" height="82" rx="8" class="fill-blue-50 dark:fill-blue-950/60 stroke-blue-200 dark:stroke-blue-800" stroke-width="1"/>
              <text x="20" y="168" class="fill-blue-900 dark:fill-blue-200 text-[11px] font-semibold">• Hybridization: sp² (Planar)</text>
              <text x="20" y="184" class="fill-blue-900 dark:fill-blue-200 text-[11px] font-semibold">• Bond Angle: 120°</text>
              <text x="20" y="200" class="fill-blue-900 dark:fill-blue-200 text-[11px] font-semibold">• Valence Electrons: 6 (Incomplete)</text>
              <text x="20" y="216" class="fill-blue-900 dark:fill-blue-200 text-[11px] font-bold">• Order: 3° > 2° > 1° > CH₃⁺</text>
            </g>
            
            <!-- CARBANION CARD -->
            <g transform="translate(282, 48)">
              <rect width="235" height="245" rx="12" class="fill-white dark:fill-slate-950 stroke-emerald-300 dark:stroke-emerald-700" stroke-width="1.5"/>
              <text x="117" y="24" text-anchor="middle" class="fill-emerald-700 dark:fill-emerald-400 font-bold text-xs">Carbanion (R⁻)</text>
              
              <!-- Orbital drawing -->
              <g transform="translate(117, 85)">
                <!-- Lone pair lobe -->
                <path d="M 0,0 C -22,-40 22,-40 0,0" fill="#a7f3d0" class="dark:fill-emerald-950 stroke-emerald-600 dark:stroke-emerald-400" stroke-width="1.5"/>
                <text x="0" y="-20" text-anchor="middle" class="fill-emerald-900 dark:fill-emerald-200 font-mono font-bold text-xs">: ⁻</text>
                <!-- Central Carbon -->
                <circle cx="0" cy="0" r="14" class="fill-emerald-100 dark:fill-emerald-900 stroke-emerald-600 dark:stroke-emerald-400" stroke-width="2"/>
                <text x="0" y="4" text-anchor="middle" class="fill-emerald-900 dark:fill-emerald-100 font-bold text-xs">C⁻</text>
                <!-- 3 bonds pyramidal -->
                <line x1="-12" y1="8" x2="-35" y2="35" stroke="#334155" stroke-width="2"/>
                <line x1="12" y1="8" x2="35" y2="35" stroke="#334155" stroke-width="2"/>
                <line x1="0" y1="14" x2="0" y2="42" stroke="#334155" stroke-width="2"/>
              </g>
              
              <rect x="12" y="150" width="211" height="82" rx="8" class="fill-emerald-50 dark:fill-emerald-950/60 stroke-emerald-200 dark:stroke-emerald-800" stroke-width="1"/>
              <text x="20" y="168" class="fill-emerald-900 dark:fill-emerald-200 text-[11px] font-semibold">• Hybridization: sp³ (Pyramidal)</text>
              <text x="20" y="184" class="fill-emerald-900 dark:fill-emerald-200 text-[11px] font-semibold">• Bond Angle: ~107°</text>
              <text x="20" y="200" class="fill-emerald-900 dark:fill-emerald-200 text-[11px] font-semibold">• Valence Electrons: 8 (Complete)</text>
              <text x="20" y="216" class="fill-emerald-900 dark:fill-emerald-200 text-[11px] font-bold">• Order: CH₃⁻ > 1° > 2° > 3°</text>
            </g>
            
            <!-- FREE RADICAL CARD -->
            <g transform="translate(540, 48)">
              <rect width="235" height="245" rx="12" class="fill-white dark:fill-slate-950 stroke-amber-300 dark:stroke-amber-700" stroke-width="1.5"/>
              <text x="117" y="24" text-anchor="middle" class="fill-amber-700 dark:fill-amber-400 font-bold text-xs">Free Radical (R•)</text>
              
              <!-- Orbital drawing -->
              <g transform="translate(117, 85)">
                <!-- 2p lobe with 1 dot -->
                <path d="M 0,0 C -20,-35 20,-35 0,0 C -20,35 20,35 0,0" fill="none" stroke="#d97706" stroke-width="2" stroke-dasharray="3,2"/>
                <circle cx="0" cy="-20" r="3.5" fill="#d97706"/>
                <text x="0" y="-38" text-anchor="middle" class="fill-amber-600 dark:fill-amber-400 font-bold text-[10px]">Unpaired e⁻ in p</text>
                <!-- Central Carbon -->
                <circle cx="0" cy="0" r="14" class="fill-amber-100 dark:fill-amber-900 stroke-amber-600 dark:stroke-amber-400" stroke-width="2"/>
                <text x="0" y="4" text-anchor="middle" class="fill-amber-900 dark:fill-amber-100 font-bold text-xs">C•</text>
                <!-- 3 bonds planar -->
                <line x1="-14" y1="0" x2="-45" y2="-10" stroke="#334155" stroke-width="2"/>
                <line x1="14" y1="0" x2="45" y2="-10" stroke="#334155" stroke-width="2"/>
                <line x1="0" y1="14" x2="0" y2="45" stroke="#334155" stroke-width="2"/>
              </g>
              
              <rect x="12" y="150" width="211" height="82" rx="8" class="fill-amber-50 dark:fill-amber-950/60 stroke-amber-200 dark:stroke-amber-800" stroke-width="1"/>
              <text x="20" y="168" class="fill-amber-900 dark:fill-amber-200 text-[11px] font-semibold">• Hybridization: sp² (Planar)</text>
              <text x="20" y="184" class="fill-amber-900 dark:fill-amber-200 text-[11px] font-semibold">• Paramagnetic (Unpaired e⁻)</text>
              <text x="20" y="200" class="fill-amber-900 dark:fill-amber-200 text-[11px] font-semibold">• Valence Electrons: 7 (Odd e⁻)</text>
              <text x="20" y="216" class="fill-amber-900 dark:fill-amber-200 text-[11px] font-bold">• Order: 3° > 2° > 1° > CH₃•</text>
            </g>
          </svg>`
        }
      ],
      importantPoints: [
        '🎯 NEET Hyperconjugation Alpha-H Counting Rule for Carbocations & Radicals: Count the number of H atoms on sp³ carbons attached DIRECTLY to the C⁺ or C•. (CH₃)₃C⁺ has 9 α-H (most stable); (CH₃)₂CH⁺ has 6 α-H; CH₃CH₂⁺ has 3 α-H; CH₃⁺ has 0 α-H.',
        'Carbanion Reverse Trend: In carbanions, alkyl groups supply electron density via +I effect onto a carbon that is already negatively charged. More alkyl groups = higher electron repulsion = lower stability (CH₃⁻ > 1° > 2° > 3°).'
      ]
    },
    {
      heading: '4. Curved-Arrow Notation & Mechanism Rules',
      paragraphs: [
        'Curved arrows are the fundamental graphic language of organic chemistry mechanisms. They track the exact movement of valence electrons during bond cleavage and bond formation steps.',
        'Essential Rules for Drawing Curved Arrows in NEET:',
        '1. Electrons flow from Electron Source to Electron Sink: Arrow tails must always start at a lone pair (:), a π-bond (═), or a σ-bond (─). Arrow heads point directly to the specific atom accepting the electron pair or the space where a new bond is forming.',
        '2. NEVER draw an arrow starting from a positive charge (+) or a hydrogen nucleus! A positive charge is an empty space (sink), not an electron source.',
        '3. Double-Headed Curved Arrow (↷): Indicates the movement of a full pair of electrons (2 e⁻). Used in heterolysis, nucleophilic attack, and resonance.',
        '4. Fishhook Arrow (rightharpoonup): Indicates the movement of a single electron (1 e⁻). Used exclusively in homolysis and free radical reactions.',
        '5. Conservation of Charge: The sum of formal charges on the reactant side MUST equal the sum of formal charges on the product side in every elementary mechanism step.'
      ],
      visuals: [
        {
          caption: 'Correct vs Incorrect Curved Arrow Mechanisms: Examples of electron flow notation.',
          guide: 'Green checkmarks highlight correct electron pair movement from nucleophile lone pair to electrophile. Red crosses point out common student errors.',
          svgContent: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 240" class="w-full h-auto rounded-xl bg-slate-50 dark:bg-slate-900 font-sans border border-slate-200 dark:border-slate-800">
            <rect width="800" height="240" rx="16" fill="#f8fafc" class="dark:fill-slate-900"/>
            <text x="400" y="28" text-anchor="middle" class="fill-slate-900 dark:fill-slate-100 font-black text-sm">Curved Arrow Rules: Correct vs Incorrect Mechanism Notation</text>
            
            <!-- CORRECT PANEL -->
            <g transform="translate(30, 48)">
              <rect width="355" height="170" rx="12" class="fill-white dark:fill-slate-950 stroke-emerald-400 dark:stroke-emerald-600" stroke-width="2"/>
              <text x="177" y="24" text-anchor="middle" class="fill-emerald-700 dark:fill-emerald-400 font-bold text-xs">✓ CORRECT: Arrow Starts from Electron Source (Lone Pair)</text>
              
              <text x="177" y="65" text-anchor="middle" class="fill-slate-900 dark:fill-slate-100 font-mono font-bold text-sm">H𝜄O:   +   H⁺   ──►   H₃O⁺</text>
              
              <!-- Curved arrow from lone pair to H+ -->
              <path d="M 125,52 C 140,25 180,25 200,52" fill="none" stroke="#059669" stroke-width="2.5"/>
              <polygon points="200,52 192,46 193,56" fill="#059669"/>
              
              <rect x="15" y="95" width="325" height="60" rx="8" class="fill-emerald-50 dark:fill-emerald-950/60 stroke-emerald-200 dark:stroke-emerald-800" stroke-width="1"/>
              <text x="25" y="118" class="fill-emerald-900 dark:fill-emerald-200 text-[11px] font-semibold">Tail starts at oxygen lone pair (e⁻ source).</text>
              <text x="25" y="138" class="fill-emerald-900 dark:fill-emerald-200 text-[11px] font-semibold">Head points to H⁺ proton (e⁻ sink).</text>
            </g>
            
            <!-- INCORRECT PANEL -->
            <g transform="translate(415, 48)">
              <rect width="355" height="170" rx="12" class="fill-white dark:fill-slate-950 stroke-rose-400 dark:stroke-rose-600" stroke-width="2"/>
              <text x="177" y="24" text-anchor="middle" class="fill-rose-700 dark:fill-rose-400 font-bold text-xs">✗ INCORRECT: Arrow Starts from Positive Charge</text>
              
              <text x="177" y="65" text-anchor="middle" class="fill-slate-900 dark:fill-slate-100 font-mono font-bold text-sm">H⁺   ──►   :OH₂   (WRONG!)</text>
              
              <!-- Wrong arrow from H+ -->
              <path d="M 125,52 C 140,25 180,25 200,52" fill="none" stroke="#e11d48" stroke-width="2.5" stroke-dasharray="4,3"/>
              <polygon points="200,52 192,46 193,56" fill="#e11d48"/>
              
              <rect x="15" y="95" width="325" height="60" rx="8" class="fill-rose-50 dark:fill-rose-950/60 stroke-rose-200 dark:stroke-rose-800" stroke-width="1"/>
              <text x="25" y="118" class="fill-rose-900 dark:fill-rose-200 text-[11px] font-semibold">FATAL ERROR: H⁺ has NO electrons!</text>
              <text x="25" y="138" class="fill-rose-900 dark:fill-rose-200 text-[11px] font-semibold">Curved arrows represent electron movement, NOT proton movement.</text>
            </g>
          </svg>`
        }
      ],
      importantPoints: [
        '🎯 NEET Fundamental Rule: Curved arrows always move from HIGH electron density (lone pairs, π-bonds, negative charges) to LOW electron density (vacant orbitals, positive charges, electronegative sinks).'
      ]
    },
    {
      heading: '5. Four Fundamental Types of Organic Reactions',
      paragraphs: [
        'All organic reactions in the NEET syllabus fall into four core mechanistic categories based on structural transformations:',
        '1. Substitution Reactions: Replacement of an atom or group attached to carbon by an attacking reagent.',
        '• Nucleophilic Substitution (SN1 vs SN2): SN1 proceeds in 2 steps via a carbocation intermediate (racemization, rate = k[R-X], 3° > 2° > 1°). SN2 proceeds in 1 concerted step via a 5-coordinate transition state (100% Walden inversion, rate = k[R-X][Nu⁻], 1° > 2° > 3°).',
        '• Electrophilic Substitution (SEAr): Characteristic of aromatic compounds like Benzene (Nitration, Halogenation, Sulfonation, Friedel-Crafts alkylation/acylation).',
        '• Free Radical Substitution: Halogenation of alkanes (CH₄ + Cl₂ → CH₃Cl + HCl in sunlight via initiation, propagation, and termination steps).',
        '2. Addition Reactions: Unsaturated molecules (>C=C<, -C≡C-, >C=O) react with reagents to form single saturated products with 100% atom economy.',
        '• Electrophilic Addition (EA): Characteristic of alkenes/alkynes. Addition of HX follows Markovnikov Rule (electrophile H⁺ adds to the carbon carrying more hydrogen atoms to yield the more stable carbocation).',
        '• Nucleophilic Addition (NA): Characteristic of aldehydes and ketones (>C=O). Nucleophile (e.g., CN⁻ in HCN addition) attacks the electropositive carbonyl carbon.',
        '• Free Radical Addition: Anti-Markovnikov addition of HBr to alkenes in the presence of peroxides (Kharasch effect) via bromine free radical (Br•).',
        '3. Elimination Reactions: Removal of two atoms or groups from adjacent carbons to generate a double or triple bond (β-elimination). Follows Saytzeff / Zaitsev Rule (more substituted, more stable alkene is the major product).',
        '4. Rearrangement Reactions: Migration of an atom or group from one carbon to another within the same molecule to yield a structural isomer. Most commonly involves 1,2-hydride or 1,2-methyl shifts converting a less stable carbocation into a more stable 3° or allylic/benzylic carbocation.'
      ],
      visuals: [
        {
          caption: 'Comprehensive Matrix comparing Substitution, Addition, Elimination, and Rearrangement reactions.',
          guide: 'Substitution replaces a group; Addition breaks a π-bond to add two groups; Elimination removes two groups to create a π-bond; Rearrangement rearranges the molecular skeleton.',
          svgContent: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 320" class="w-full h-auto rounded-xl bg-slate-50 dark:bg-slate-900 font-sans border border-slate-200 dark:border-slate-800">
            <rect width="800" height="320" rx="16" fill="#f8fafc" class="dark:fill-slate-900"/>
            <text x="400" y="28" text-anchor="middle" class="fill-slate-900 dark:fill-slate-100 font-black text-sm">Four Fundamental Types of Organic Reactions in NEET</text>
            
            <!-- GRID 2x2 -->
            <!-- 1. SUBSTITUTION -->
            <g transform="translate(25, 48)">
              <rect width="360" height="120" rx="10" class="fill-white dark:fill-slate-950 stroke-blue-300 dark:stroke-blue-700" stroke-width="1.5"/>
              <text x="180" y="22" text-anchor="middle" class="fill-blue-700 dark:fill-blue-400 font-bold text-xs">1. Substitution Reaction</text>
              <text x="180" y="50" text-anchor="middle" class="fill-slate-900 dark:fill-slate-100 font-mono font-bold text-xs">R ─ X  +  Nu⁻   ──►   R ─ Nu  +  X⁻</text>
              <rect x="15" y="65" width="330" height="42" rx="6" class="fill-blue-50 dark:fill-blue-950/60"/>
              <text x="180" y="82" text-anchor="middle" class="fill-blue-900 dark:fill-blue-200 text-[11px] font-semibold">Leaving group X⁻ replaced by Nucleophile Nu⁻.</text>
              <text x="180" y="98" text-anchor="middle" class="fill-blue-900 dark:fill-blue-200 text-[10px]">Examples: SN1, SN2, SEAr in Benzene, Free Radical Chlorination</text>
            </g>
            
            <!-- 2. ADDITION -->
            <g transform="translate(415, 48)">
              <rect width="360" height="120" rx="10" class="fill-white dark:fill-slate-950 stroke-emerald-300 dark:stroke-emerald-700" stroke-width="1.5"/>
              <text x="180" y="22" text-anchor="middle" class="fill-emerald-700 dark:fill-emerald-400 font-bold text-xs">2. Addition Reaction</text>
              <text x="180" y="50" text-anchor="middle" class="fill-slate-900 dark:fill-slate-100 font-mono font-bold text-xs">>C ═ C<  +  A ─ B   ──►   >C(A) ─ C(B)<</text>
              <rect x="15" y="65" width="330" height="42" rx="6" class="fill-emerald-50 dark:fill-emerald-950/60"/>
              <text x="180" y="82" text-anchor="middle" class="fill-emerald-900 dark:fill-emerald-200 text-[11px] font-semibold">π-bond breaks; two new σ-bonds form.</text>
              <text x="180" y="98" text-anchor="middle" class="fill-emerald-900 dark:fill-emerald-200 text-[10px]">Examples: Electrophilic Addition (HX to Alkenes), HCN to >C=O</text>
            </g>
            
            <!-- 3. ELIMINATION -->
            <g transform="translate(25, 180)">
              <rect width="360" height="120" rx="10" class="fill-white dark:fill-slate-950 stroke-purple-300 dark:stroke-purple-700" stroke-width="1.5"/>
              <text x="180" y="22" text-anchor="middle" class="fill-purple-700 dark:fill-purple-400 font-bold text-xs">3. Elimination Reaction</text>
              <text x="180" y="50" text-anchor="middle" class="fill-slate-900 dark:fill-slate-100 font-mono font-bold text-xs">─C(H) ─ C(X)─   +   Base   ──►   >C ═ C<  +  HX</text>
              <rect x="15" y="65" width="330" height="42" rx="6" class="fill-purple-50 dark:fill-purple-950/60"/>
              <text x="180" y="82" text-anchor="middle" class="fill-purple-900 dark:fill-purple-200 text-[11px] font-semibold">Two σ-bonds lost; new π-bond formed (Saytzeff Alkene).</text>
              <text x="180" y="98" text-anchor="middle" class="fill-purple-900 dark:fill-purple-200 text-[10px]">Examples: Dehydrohalogenation of alkyl halides with alc. KOH (E1/E2)</text>
            </g>
            
            <!-- 4. REARRANGEMENT -->
            <g transform="translate(415, 180)">
              <rect width="360" height="120" rx="10" class="fill-white dark:fill-slate-950 stroke-amber-300 dark:stroke-amber-700" stroke-width="1.5"/>
              <text x="180" y="22" text-anchor="middle" class="fill-amber-700 dark:fill-amber-400 font-bold text-xs">4. Rearrangement Reaction</text>
              <text x="180" y="50" text-anchor="middle" class="fill-slate-900 dark:fill-slate-100 font-mono font-bold text-xs">(CH₃)₂CH─C⁺H₂   ──► (1,2-H⁻ shift) ──►   (CH₃)₂C⁺─CH₃</text>
              <rect x="15" y="65" width="330" height="42" rx="6" class="fill-amber-50 dark:fill-amber-950/60"/>
              <text x="180" y="82" text-anchor="middle" class="fill-amber-900 dark:fill-amber-200 text-[11px] font-semibold">1° Carbocation rearranges to more stable 3° Carbocation.</text>
              <text x="180" y="98" text-anchor="middle" class="fill-amber-900 dark:fill-amber-200 text-[10px]">Examples: 1,2-Hydride shift, 1,2-Methyl shift in SN1/E1 reactions</text>
            </g>
          </svg>`
        }
      ],
      importantPoints: [
        '🎯 NEET Rearrangement Rule: Rearrangement of carbocations occurs ONLY when it results in a MORE STABLE carbocation. A 1° carbocation will shift to 2° or 3°, or an alkyl carbocation will shift to allylic/benzylic. A 3° carbocation will NEVER rearrange to a 2° or 1° carbocation!'
      ]
    },
    {
      heading: '8. Worked NEET Problem-Solving Examples',
      paragraphs: [
        'Study these step-by-step solved examples covering high-yield reaction mechanisms and intermediate stability patterns tested in NEET UG.'
      ],
      examples: [
        {
          problem: 'Identify which of the following species behave as Electrophiles and which behave as Nucleophiles: (a) BF₃, (b) OH⁻, (c) NO₂⁺, (d) NH₃, (e) AlCl₃, (f) H₂O.',
          solution: 'Step 1: Define criteria for Electrophiles (electron acceptors / Lewis acids) and Nucleophiles (electron donors / Lewis bases).\nStep 2: Analyze each species:\n• (a) BF₃: Boron has 6 valence electrons (incomplete octet, vacant p-orbital) → Neutral Electrophile.\n• (b) OH⁻: Positively charged with 3 lone pairs and negative formal charge → Negatively Charged Nucleophile.\n• (c) NO₂⁺: Positively charged nitronium ion with empty orbital → Positively Charged Electrophile.\n• (d) NH₃: Nitrogen has 1 unshared lone pair → Neutral Nucleophile.\n• (e) AlCl₃: Aluminium has 6 valence electrons (incomplete octet) → Neutral Electrophile.\n• (f) H₂O: Oxygen has 2 unshared lone pairs → Neutral Nucleophile.\nConclusion:\nElectrophiles: BF₃, NO₂⁺, AlCl₃\nNucleophiles: OH⁻, NH₃, H₂O.',
          answer: 'Electrophiles: BF₃, NO₂⁺, AlCl₃ | Nucleophiles: OH⁻, NH₃, H₂O'
        },
        {
          problem: 'When 3-methylbutan-2-ol is treated with concentrated H₂SO₄, it undergoes acid-catalyzed dehydration to form an alkene. Predict the carbocation intermediate formed initially and its subsequent rearrangement product.',
          solution: 'Step 1: Protonation of alcohol OH group yields 3-methylbutan-2-yl oxonium ion, which loses H₂O to form a Secondary (2°) Carbocation: CH₃-CH(CH₃)-C⁺H-CH₃.\nStep 2: Analyze α-hydrogen/alkyl environment on adjacent carbons. C2 is attached to C3 carrying a hydrogen and two methyl groups.\nStep 3: A 1,2-hydride shift (:H⁻) occurs from C3 to C2:\nCH₃-C⁺(CH₃)-CH₂-CH₃ (Tertiary 3° Carbocation).\nStep 4: The 3° carbocation has 8 hyperconjugative α-hydrogens (highly stable) compared to 4 α-hydrogens in the 2° carbocation.\nStep 5: Loss of H⁺ from the 3° carbocation gives the Saytzeff major product: 2-methylbut-2-ene.',
          answer: 'Initial: 2° Carbocation [CH₃-CH(CH₃)-C⁺H-CH₃] ──► Rearranged: 3° Carbocation [CH₃-C⁺(CH₃)-CH₂-CH₃]'
        },
        {
          problem: 'Arrange the following carbanions in increasing order of stability: (I) CH₃-CH₂⁻, (II) HC≡C⁻, (III) CH₂=CH⁻, (IV) (CH₃)₃C⁻.',
          solution: 'Step 1: Recall factors affecting carbanion stability: (a) Hybridization / % s-character of negative carbon, (b) Inductive (+I) effect of alkyl groups.\nStep 2: Evaluate hybridization:\n• (II) HC≡C⁻: sp hybridized carbon (50% s-character) → Highest electronegativity, holds negative charge closest to nucleus → Most Stable!\n• (III) CH₂=CH⁻: sp² hybridized carbon (33.3% s-character) → Moderately stable.\n• (I) CH₃-CH₂⁻: sp³ hybridized carbon with 1 alkyl group (+I) → Less stable.\n• (IV) (CH₃)₃C⁻: 3° carbanion with 3 alkyl groups (+I) pumping electron density → Least Stable!\nConclusion / Increasing Order of Stability:\n(IV) (CH₃)₃C⁻ < (I) CH₃-CH₂⁻ < (III) CH₂=CH⁻ < (II) HC≡C⁻.',
          answer: '(IV) (CH₃)₃C⁻ < (I) CH₃-CH₂⁻ < (III) CH₂=CH⁻ < (II) HC≡C⁻'
        }
      ]
    }
  ],

  commonConfusions: [
    {
      commonConfusion: 'Assuming neutral molecules cannot act as electrophiles or nucleophiles.',
      correctFact: 'BF₃, AlCl₃, FeCl₃, SO₃, and CO₂ are powerful neutral electrophiles (vacant orbitals). H₂O, NH₃, R-OH, and R-NH₂ are powerful neutral nucleophiles (unshared lone pairs).',
      whyItMattersForNEET: 'Frequently tested in NEET identification questions where students incorrectly assume only charged species react.'
    },
    {
      commonConfusion: 'Expecting carbocation rearrangement during SN2 or E2 reactions.',
      correctFact: 'Rearrangements occur ONLY in reactions that form a FREE carbocation intermediate (SN1 and E1). SN2 and E2 proceed via concerted transition states with NO free carbocations, so rearrangement is IMPOSSIBLE.',
      whyItMattersForNEET: 'Prevents students from choosing incorrect rearranged products in SN2/E2 reaction questions.'
    },
    {
      commonConfusion: 'Applying the carbocation stability trend (3° > 2° > 1° > CH₃⁺) to carbanions.',
      correctFact: 'Carbanions have the EXACT REVERSE stability trend: CH₃⁻ > 1° > 2° > 3°. Alkyl groups exert +I effect, destabilizing the negative charge.',
      whyItMattersForNEET: 'Direct question in NEET on comparing carbanion relative stabilities.'
    },
    {
      commonConfusion: 'Drawing curved arrows starting from positive charges or hydrogen atoms.',
      correctFact: 'Curved arrows MUST always originate at electron-rich sources (lone pairs, π-bonds, negative charge) and point toward electron sinks.',
      whyItMattersForNEET: 'Critical for mechanism assertion-reason and correct notation questions in NCERT.'
    }
  ],

  neetImportantPoints: [
    '🎯 HELP Rule for Free Radicals: Heat, Electricity, Light (hν), and Peroxides induce homolytic bond fission yielding free radicals.',
    '🎯 Ambident Nucleophiles: CN⁻ and NO₂⁻ carry two nucleophilic donor sites. AgCN yields alkyl isocyanides (R-NC), while KCN yields alkyl cyanides (R-CN).',
    '🎯 Carbocation Rearrangement: 1° carbocations adjacent to 2°/3° carbons spontaneously undergo 1,2-hydride (:H⁻) or 1,2-methyl (:CH₃⁻) shifts to maximize stability.',
    '🎯 Hybridization and Carbanion Stability: HC≡C⁻ (sp, 50% s-character) is MORE stable than CH₂=CH⁻ (sp², 33.3%) and CH₃-CH₂⁻ (sp³, 25%).',
    '🎯 Peroxide Effect Limitation: The Anti-Markovnikov addition of HBr in the presence of peroxide operates ONLY with HBr. It fails with HCl and HI because the propagation steps are endothermic.'
  ],

  formulae: [
    {
      title: 'Heterolytic Cleavage Formula',
      formula: 'A-B \\xrightarrow{\\text{Heterolysis}} A^+ + :B^-',
      variables: 'A = Electron-deficient fragment (Cation); B = Electron-rich fragment (Anion).',
      whenToUse: 'Use when analyzing polar reactions forming carbocations, carbanions, or ionic intermediates.',
      note: 'Favoured by polar protic solvents that solvate the generated ions.'
    },
    {
      title: 'Homolytic Cleavage Formula',
      formula: 'A-B \\xrightarrow[h\\nu \\text{ or } \\Delta]{\\text{Homolysis}} A^\\bullet + B^\\bullet',
      variables: 'A•, B• = Neutral free radicals with 1 unpaired electron.',
      whenToUse: 'Use in free-radical halogenation or peroxide-catalyzed addition reactions.',
      note: 'Initiated by Heat (Δ), Light (hν), Electricity, or Peroxides (HELP rule).'
    },
    {
      title: 'Hyperconjugative Alpha-Hydrogen Count',
      formula: 'N_{\\text{structures}} = N_{\\alpha\\text{-H}} + 1',
      variables: 'N_structures = Number of hyperconjugative resonance forms; N_α-H = Alpha-hydrogens on sp³ carbons.',
      whenToUse: 'Use to determine relative stability of carbocations and free radicals.',
      note: '3° alkyl (9 α-H) > 2° alkyl (6 α-H) > 1° alkyl (3 α-H) > methyl (0 α-H).'
    }
  ],

  practiceQuestions: [
  {
    "id": "practice-mech-1",
    "question": "Which of the following is a neutral electrophile?",
    "options": [
      "OH⁻",
      "NH₃",
      "BF₃",
      "CN⁻"
    ],
    "correctAnswer": 2,
    "explanation": "BF₃ is a neutral electrophile (Lewis acid) because boron has 6 valence electrons (incomplete octet) and an empty p-orbital capable of accepting electron pairs.",
    "difficulty": "Easy",
    "topicId": "chem-basic-reaction-mechanisms",
    "conceptTested": "Identification of Electrophiles"
  },
  {
    "id": "practice-mech-2",
    "question": "In which reaction pathway does carbocation rearrangement NOT occur?",
    "options": [
      "SN1 reaction",
      "E1 reaction",
      "SN2 reaction",
      "Dehydration of alcohol with H₂SO₄"
    ],
    "correctAnswer": 2,
    "explanation": "SN2 proceeds via a single-step concerted transition state with NO free carbocation intermediate, making carbocation rearrangement impossible. SN1, E1, and alcohol dehydration generate free carbocations that readily rearrange.",
    "difficulty": "Medium",
    "topicId": "chem-basic-reaction-mechanisms",
    "conceptTested": "Carbocation Rearrangement Conditions"
  },
  {
    "id": "practice-mech-3",
    "question": "Which of the following carbanions is the LEAST stable?",
    "options": [
      "CH₃⁻",
      "CH₃-CH₂⁻",
      "(CH₃)₂CH⁻",
      "(CH₃)₃C⁻"
    ],
    "correctAnswer": 3,
    "explanation": "Alkyl groups exert an electron-donating (+I) inductive effect, which increases negative charge density on the carbanion carbon and destabilizes it. Therefore, 3° carbanion (CH₃)₃C⁻ is the least stable.",
    "difficulty": "Easy",
    "topicId": "chem-basic-reaction-mechanisms",
    "conceptTested": "Carbanion Stability Order"
  },
  {
    "id": "prac-chembasicreactionmechanisms-4",
    "question": "Regarding Basic Organic Reaction Mechanisms, which of the following statements correctly resolves a common misconception about \"Assuming neutral molecules cannot act as electrophiles or nucleophiles.\"?",
    "options": [
      "BF₃, AlCl₃, FeCl₃, SO₃, and CO₂ are powerful neutral electrophiles (vacant orbitals). H₂O, NH₃, R-OH, and R-NH₂ are powerful neutral nucleophiles (unshared lone pairs).",
      "Incorrect assumption: Assuming neutral molecules cannot act as electrophiles or nucleophiles.",
      "Both statements are invalid under standard conditions",
      "Neither statement applies to NEET examination scope"
    ],
    "correctAnswer": 0,
    "explanation": "BF₃, AlCl₃, FeCl₃, SO₃, and CO₂ are powerful neutral electrophiles (vacant orbitals). H₂O, NH₃, R-OH, and R-NH₂ are powerful neutral nucleophiles (unshared lone pairs).. Frequently tested in NEET identification questions where students incorrectly assume only charged species react.",
    "difficulty": "Medium",
    "conceptTested": "Basic Organic Reaction Mechanisms - Conceptual Clarity"
  },
  {
    "id": "prac-chembasicreactionmechanisms-5",
    "question": "Regarding Basic Organic Reaction Mechanisms, which of the following statements correctly resolves a common misconception about \"Expecting carbocation rearrangement during SN2 or E2 reactions.\"?",
    "options": [
      "Rearrangements occur ONLY in reactions that form a FREE carbocation intermediate (SN1 and E1). SN2 and E2 proceed via concerted transition states with NO free carbocations, so rearrangement is IMPOSSIBLE.",
      "Incorrect assumption: Expecting carbocation rearrangement during SN2 or E2 reactions.",
      "Both statements are invalid under standard conditions",
      "Neither statement applies to NEET examination scope"
    ],
    "correctAnswer": 0,
    "explanation": "Rearrangements occur ONLY in reactions that form a FREE carbocation intermediate (SN1 and E1). SN2 and E2 proceed via concerted transition states with NO free carbocations, so rearrangement is IMPOSSIBLE.. Prevents students from choosing incorrect rearranged products in SN2/E2 reaction questions.",
    "difficulty": "Medium",
    "conceptTested": "Basic Organic Reaction Mechanisms - Conceptual Clarity"
  },
  {
    "id": "prac-chembasicreactionmechanisms-6",
    "question": "Regarding Basic Organic Reaction Mechanisms, which of the following statements correctly resolves a common misconception about \"Applying the carbocation stability trend (3° > 2° > 1° > CH₃⁺) to carbanions.\"?",
    "options": [
      "Carbanions have the EXACT REVERSE stability trend: CH₃⁻ > 1° > 2° > 3°. Alkyl groups exert +I effect, destabilizing the negative charge.",
      "Incorrect assumption: Applying the carbocation stability trend (3° > 2° > 1° > CH₃⁺) to carbanions.",
      "Both statements are invalid under standard conditions",
      "Neither statement applies to NEET examination scope"
    ],
    "correctAnswer": 0,
    "explanation": "Carbanions have the EXACT REVERSE stability trend: CH₃⁻ > 1° > 2° > 3°. Alkyl groups exert +I effect, destabilizing the negative charge.. Direct question in NEET on comparing carbanion relative stabilities.",
    "difficulty": "Medium",
    "conceptTested": "Basic Organic Reaction Mechanisms - Conceptual Clarity"
  },
  {
    "id": "prac-chembasicreactionmechanisms-7",
    "question": "Regarding Basic Organic Reaction Mechanisms, which of the following statements correctly resolves a common misconception about \"Drawing curved arrows starting from positive charges or hydrogen atoms.\"?",
    "options": [
      "Curved arrows MUST always originate at electron-rich sources (lone pairs, π-bonds, negative charge) and point toward electron sinks.",
      "Incorrect assumption: Drawing curved arrows starting from positive charges or hydrogen atoms.",
      "Both statements are invalid under standard conditions",
      "Neither statement applies to NEET examination scope"
    ],
    "correctAnswer": 0,
    "explanation": "Curved arrows MUST always originate at electron-rich sources (lone pairs, π-bonds, negative charge) and point toward electron sinks.. Critical for mechanism assertion-reason and correct notation questions in NCERT.",
    "difficulty": "Medium",
    "conceptTested": "Basic Organic Reaction Mechanisms - Conceptual Clarity"
  },
  {
    "id": "prac-chembasicreactionmechanisms-8",
    "question": "In the study of Basic Organic Reaction Mechanisms, what is the exact definition and significance of \"Homolytic Cleavage (Homolysis)\"?",
    "options": [
      "Symmetrical breaking of a covalent bond where each bonded atom retains one electron from the shared electron pair, producing two neutral free radicals.",
      "An unrelated metabolic process in plants",
      "A secondary non-functional structural component",
      "An experimental artifact observed only in vitro"
    ],
    "correctAnswer": 0,
    "explanation": "Symmetrical breaking of a covalent bond where each bonded atom retains one electron from the shared electron pair, producing two neutral free radicals.. Favoured by UV light (hν), peroxides (R-O-O-R), high temperatures (>500°C), and non-polar gas-phase conditions (HELP rule: Heat, Electricity, Light, Peroxides).",
    "difficulty": "Easy",
    "conceptTested": "Homolytic Cleavage (Homolysis) definition"
  },
  {
    "id": "prac-chembasicreactionmechanisms-9",
    "question": "In the study of Basic Organic Reaction Mechanisms, what is the exact definition and significance of \"Heterolytic Cleavage (Heterolysis)\"?",
    "options": [
      "Unsymmetrical breaking of a covalent bond where both bonding electrons are retained by the more electronegative atom, forming a cation and an anion.",
      "An unrelated metabolic process in plants",
      "A secondary non-functional structural component",
      "An experimental artifact observed only in vitro"
    ],
    "correctAnswer": 0,
    "explanation": "Unsymmetrical breaking of a covalent bond where both bonding electrons are retained by the more electronegative atom, forming a cation and an anion.. Favoured by polar protic solvents (H₂O, EtOH) and produces carbocations (R⁺) or carbanions (R⁻).",
    "difficulty": "Easy",
    "conceptTested": "Heterolytic Cleavage (Heterolysis) definition"
  },
  {
    "id": "prac-chembasicreactionmechanisms-10",
    "question": "In the study of Basic Organic Reaction Mechanisms, what is the exact definition and significance of \"Free Radical (R•)\"?",
    "options": [
      "A neutral chemical species carrying an unpaired valence electron generated by homolytic bond fission.",
      "An unrelated metabolic process in plants",
      "A secondary non-functional structural component",
      "An experimental artifact observed only in vitro"
    ],
    "correctAnswer": 0,
    "explanation": "A neutral chemical species carrying an unpaired valence electron generated by homolytic bond fission.. Paramagnetic, highly reactive, sp² hybridized (planar), possessing 7 valence electrons.",
    "difficulty": "Easy",
    "conceptTested": "Free Radical (R•) definition"
  }
],
  pyqs: [
    {
      id: 'pyq-mechanisms-1',
      year: 2023,
      exam: 'NEET UG 2023',
      question: 'Which of the following species acts as an electrophile in the nitration of benzene?',
      options: ['NO₂⁻', 'NO₂⁺', 'NO⁺', 'HNO₃'],
      correctAnswer: 1,
      explanation: 'In the nitration of benzene using a mixture of concentrated HNO₃ and concentrated H₂SO₄, H₂SO₄ protonates HNO₃ to generate the nitronium ion (NO₂⁺). NO₂⁺ is a powerful electrophile that attacks the aromatic benzene ring.',
      conceptTested: 'Electrophiles in Aromatic Substitution',
      difficulty: 'Easy',
      verified: true,
      classification: 'Direct',
      marks: 4,
      topicId: 'chem-basic-reaction-mechanisms'
    },
    {
      id: 'pyq-mechanisms-2',
      year: 2022,
      exam: 'NEET UG 2022',
      question: 'Which among the following species is a neutral electrophile?',
      options: ['H₂O', 'NH₃', 'BF₃', 'OH⁻'],
      correctAnswer: 2,
      explanation: 'Boron trifluoride (BF₃) has 6 valence electrons around the central Boron atom (an incomplete octet). It possesses a vacant 2p orbital capable of accepting an electron pair, making it a neutral electrophile (Lewis acid). H₂O and NH₃ are neutral nucleophiles, while OH⁻ is an anionic nucleophile.',
      conceptTested: 'Identification of Neutral Electrophiles',
      difficulty: 'Easy',
      verified: true,
      classification: 'Direct',
      marks: 4,
      topicId: 'chem-basic-reaction-mechanisms'
    },
    {
      id: 'pyq-mechanisms-3',
      year: 2021,
      exam: 'NEET UG 2021',
      question: 'Homolytic cleavage of a covalent C─C bond results in the formation of:',
      options: ['Carbocations', 'Carbanions', 'Free Radicals', 'Electrophiles'],
      correctAnswer: 2,
      explanation: 'Homolytic cleavage (symmetrical bond fission) divides the shared bonding electron pair equally between the two bonded atoms, producing two neutral free radicals each carrying one unpaired electron.',
      conceptTested: 'Homolytic Bond Cleavage',
      difficulty: 'Easy',
      verified: true,
      classification: 'Direct',
      marks: 4,
      topicId: 'chem-basic-reaction-mechanisms'
    },
    {
      id: 'pyq-mechanisms-4',
      year: 2020,
      exam: 'NEET UG 2020',
      question: 'Which of the following alkyl carbocations is the most stable?',
      options: ['(CH₃)₃C⁺', '(CH₃)₂CH⁺', 'CH₃CH₂⁺', 'CH₃⁺'],
      correctAnswer: 0,
      explanation: 'The tert-butyl carbocation, (CH₃)₃C⁺, is a tertiary (3°) carbocation with 9 hyperconjugative α-hydrogens and three +I methyl groups. This provides maximum electron delocalization into the empty 2p orbital, making it the most stable alkyl carbocation.',
      conceptTested: 'Carbocation Stability Order',
      difficulty: 'Easy',
      verified: true,
      classification: 'Direct',
      marks: 4,
      topicId: 'chem-basic-reaction-mechanisms'
    },
    {
      id: 'pyq-mechanisms-5',
      year: 2019,
      exam: 'NEET UG 2019',
      question: 'Which of the following acts as a neutral nucleophile?',
      options: ['AlCl₃', 'BF₃', 'NH₃', 'H⁺'],
      correctAnswer: 2,
      explanation: 'Ammonia (NH₃) possesses an unshared lone pair of electrons on the Nitrogen atom, which it can donate to electron-deficient species, acting as a neutral nucleophile (Lewis base). AlCl₃ and BF₃ are Lewis acids (electrophiles), and H⁺ is a positively charged electrophile.',
      conceptTested: 'Identification of Neutral Nucleophiles',
      difficulty: 'Easy',
      verified: true,
      classification: 'Direct',
      marks: 4,
      topicId: 'chem-basic-reaction-mechanisms'
    },
    {
      id: 'pyq-mechanisms-6',
      year: 2018,
      exam: 'NEET UG 2018',
      question: 'The correct order of stability of alkyl free radicals is:',
      options: [
        '3° > 2° > 1° > CH₃•',
        'CH₃• > 1° > 2° > 3°',
        '3° > 1° > 2° > CH₃•',
        '1° > 2° > 3° > CH₃•'
      ],
      correctAnswer: 0,
      explanation: 'Alkyl free radicals are electron-deficient (7 valence electrons) and are stabilized by hyperconjugation from α-hydrogens and +I effect of alkyl groups. Thus, 3° (9 α-H) > 2° (6 α-H) > 1° (3 α-H) > CH₃• (0 α-H).',
      conceptTested: 'Free Radical Relative Stability',
      difficulty: 'Easy',
      verified: true,
      classification: 'Direct',
      marks: 4,
      topicId: 'chem-basic-reaction-mechanisms'
    },
    {
      id: 'pyq-mechanisms-7',
      year: 2016,
      exam: 'NEET UG 2016',
      question: 'Addition of HBr to propene in the presence of benzoyl peroxide follows which of the following mechanism pathways?',
      options: [
        'Electrophilic Addition',
        'Free Radical Addition',
        'Nucleophilic Addition',
        'Free Radical Substitution'
      ],
      correctAnswer: 1,
      explanation: 'In the presence of peroxides (R-O-O-R), HBr undergoes homolytic cleavage initiated by alkoxy radicals to produce bromine free radicals (Br•). The Br• attacks propene to form the more stable 2° free radical intermediate, resulting in Anti-Markovnikov Free Radical Addition (Kharasch Effect).',
      conceptTested: 'Peroxide Effect & Reaction Mechanisms',
      difficulty: 'Medium',
      verified: true,
      classification: 'Direct',
      marks: 4,
      topicId: 'chem-basic-reaction-mechanisms'
    },
    {
      id: 'pyq-mechanisms-8',
      year: 2015,
      exam: 'AIPMT 2015',
      question: 'The correct decreasing order of stability of simple alkyl carbanions is:',
      options: [
        'CH₃⁻ > 1° > 2° > 3°',
        '3° > 2° > 1° > CH₃⁻',
        '1° > 2° > 3° > CH₃⁻',
        '3° > 1° > 2° > CH₃⁻'
      ],
      correctAnswer: 0,
      explanation: 'Carbanions carry a negative charge (8 electrons). Alkyl groups exert electron-donating (+I) inductive effect, which increases electron density on the negative carbon, thereby destabilizing the carbanion. Therefore, methyl carbanion (CH₃⁻) with no alkyl groups is most stable, and 3° carbanion is least stable.',
      conceptTested: 'Carbanion Stability Order',
      difficulty: 'Easy',
      verified: true,
      classification: 'Direct',
      marks: 4,
      topicId: 'chem-basic-reaction-mechanisms'
    },
    {
      id: 'pyq-mechanisms-9',
      year: 2012,
      exam: 'AIPMT 2012',
      question: 'Which of the following carbanions is the most stable due to high s-character of the negatively charged carbon?',
      options: ['CH₃─CH₂⁻', 'CH₂═CH⁻', 'HC≡C⁻', '(CH₃)₃C⁻'],
      correctAnswer: 2,
      explanation: 'In HC≡C⁻, the negatively charged carbon atom is sp hybridized, containing 50% s-character. Electrons in orbitals with higher s-character are held closer to the positively charged nucleus, resulting in higher electronegativity and extraordinary stability for the carbanion.',
      conceptTested: 'Hybridization Effect on Carbanions',
      difficulty: 'Medium',
      verified: true,
      classification: 'Direct',
      marks: 4,
      topicId: 'chem-basic-reaction-mechanisms'
    },
    {
      id: 'pyq-mechanisms-10',
      year: 2010,
      exam: 'AIPMT 2010',
      question: 'The reaction CH₃Br + aq. KOH ──► CH₃OH + KBr belongs to which reaction type?',
      options: [
        'Nucleophilic Substitution (SN2)',
        'Electrophilic Substitution',
        'Elimination Reaction',
        'Electrophilic Addition'
      ],
      correctAnswer: 0,
      explanation: 'Aqueous KOH provides hydroxide nucleophile (OH⁻) which attacks the primary methyl carbon of CH₃Br from the backside in a single concerted step, displacing bromide ion (Br⁻) to form methanol via Bimolecular Nucleophilic Substitution (SN2).',
      conceptTested: 'Classification of Organic Reactions',
      difficulty: 'Easy',
      verified: true,
      classification: 'Direct',
      marks: 4,
      topicId: 'chem-basic-reaction-mechanisms'
    }
  ],

  quickRevision: [
    '🔥 BOND CLEAVAGE: Homolysis → Free Radicals (symmetrical, HELP rule); Heterolysis → Carbocation + Carbanion (unsymmetrical, polar solvent).',
    '🔥 ELECTROPHILES (E⁺): Electron-deficient (Lewis Acids). Positively charged (H⁺, NO₂⁺, Cl⁺) OR Neutral with vacant orbitals (BF₃, AlCl₃, FeCl₃, SO₃, :CH₂).',
    '🔥 NUCLEOPHILES (Nu⁻): Electron-rich (Lewis Bases). Negatively charged (OH⁻, CN⁻, RO⁻) OR Neutral with lone pairs (H₂O, NH₃, ROH). Ambident: CN⁻, NO₂⁻.',
    '🔥 CARBOCATION (R⁺): sp² planar, 6 e⁻, empty 2p orbital. Stability: 3° > 2° > 1° > CH₃⁺. Allylic/Benzylic/Tropylium possess resonance extra stability.',
    '🔥 CARBANION (R⁻): sp³ pyramidal, 8 e⁻ with lone pair. Stability: sp (HC≡C⁻) > sp² (CH₂=CH⁻) > sp³ (CH₃⁻ > 1° > 2° > 3°). Reverse of carbocations!',
    '🔥 FREE RADICAL (R•): sp² planar, 7 e⁻ (paramagnetic). Stability: 3° > 2° > 1° > CH₃• (stabilized by hyperconjugation α-H).',
    '🔥 CURVED ARROWS: ↷ = 2 e⁻ pair transfer; rightharpoonup = 1 e⁻ single electron transfer. ALWAYS draw from electron source (lone pair/bond) to electron sink.',
    '🔥 REACTION TYPES: Substitution (SN1/SN2/SEAr/Radical), Addition (Electrophilic HX, Nucleophilic HCN, Free Radical Anti-Markovnikov), Elimination (E1/E2 Saytzeff), Rearrangement (1,2-H⁻ / 1,2-CH₃⁻ shift in carbocations).'
  ]
,
  neetMarksPotential: {
  "topicName": "Basic Organic Reaction Mechanisms",
  "confidenceLabel": "HIGH",
  "confidenceText": "High Confidence: Verified against 10 official NEET/AIPMT paper appearances (10 direct questions).",
  "totalAnalyzedPapers": 15,
  "papersWithDirectPyqs": 10,
  "totalDirectPyqs": 10,
  "totalHistoricalMarks": 40,
  "averageDirectPyqsPerPaper": 0.67,
  "maxDirectPyqsInSinglePaper": 1,
  "minDirectPyqsInSinglePaper": 1,
  "minDirectMarks": 4,
  "maxDirectMarks": 4,
  "avgDirectMarksPerPaper": 2.67,
  "typicalContributionMarks": 4,
  "historicalMarksRangeText": "4 marks per paper (tested in 10 of 15 analyzed papers)",
  "whatThisMeansForYou": "Based on 10 verified direct questions across 10 unique papers, mastering Basic Organic Reaction Mechanisms gives you a historical direct score potential of ~4 marks when present.",
  "yearWiseBreakdown": [
    {
      "id": "pyq-mechanisms-1",
      "year": 2023,
      "exam": "NEET UG",
      "directPyqCount": 1,
      "marks": 4,
      "questionType": "Electrophiles in Aromatic Substitution",
      "classification": "Direct",
      "verificationStatus": "Verified (NEET UG)"
    },
    {
      "id": "pyq-mechanisms-2",
      "year": 2022,
      "exam": "NEET UG",
      "directPyqCount": 1,
      "marks": 4,
      "questionType": "Identification of Neutral Electrophiles",
      "classification": "Direct",
      "verificationStatus": "Verified (NEET UG)"
    },
    {
      "id": "pyq-mechanisms-3",
      "year": 2021,
      "exam": "NEET UG",
      "directPyqCount": 1,
      "marks": 4,
      "questionType": "Homolytic Bond Cleavage",
      "classification": "Direct",
      "verificationStatus": "Verified (NEET UG)"
    },
    {
      "id": "pyq-mechanisms-4",
      "year": 2020,
      "exam": "NEET UG",
      "directPyqCount": 1,
      "marks": 4,
      "questionType": "Carbocation Stability Order",
      "classification": "Direct",
      "verificationStatus": "Verified (NEET UG)"
    },
    {
      "id": "pyq-mechanisms-5",
      "year": 2019,
      "exam": "NEET UG",
      "directPyqCount": 1,
      "marks": 4,
      "questionType": "Identification of Neutral Nucleophiles",
      "classification": "Direct",
      "verificationStatus": "Verified (NEET UG)"
    },
    {
      "id": "pyq-mechanisms-6",
      "year": 2018,
      "exam": "NEET UG",
      "directPyqCount": 1,
      "marks": 4,
      "questionType": "Free Radical Relative Stability",
      "classification": "Direct",
      "verificationStatus": "Verified (NEET UG)"
    },
    {
      "id": "pyq-mechanisms-7",
      "year": 2016,
      "exam": "NEET UG",
      "directPyqCount": 1,
      "marks": 4,
      "questionType": "Peroxide Effect & Reaction Mechanisms",
      "classification": "Direct",
      "verificationStatus": "Verified (NEET UG)"
    },
    {
      "id": "pyq-mechanisms-8",
      "year": 2015,
      "exam": "AIPMT",
      "directPyqCount": 1,
      "marks": 4,
      "questionType": "Carbanion Stability Order",
      "classification": "Direct",
      "verificationStatus": "Verified (AIPMT)"
    },
    {
      "id": "pyq-mechanisms-9",
      "year": 2012,
      "exam": "AIPMT",
      "directPyqCount": 1,
      "marks": 4,
      "questionType": "Hybridization Effect on Carbanions",
      "classification": "Direct",
      "verificationStatus": "Verified (AIPMT)"
    },
    {
      "id": "pyq-mechanisms-10",
      "year": 2010,
      "exam": "AIPMT",
      "directPyqCount": 1,
      "marks": 4,
      "questionType": "Classification of Organic Reactions",
      "classification": "Direct",
      "verificationStatus": "Verified (AIPMT)"
    }
  ],
  "overlapPyqs": [],
  "sourceInfo": {
    "dataSource": "SATHEE (IIT Kanpur / Ministry of Education) & Official NEET Archives",
    "analysisPeriod": "2004 – 2024 (15 Verified Papers)",
    "directPyqsAnalyzedCount": 10,
    "classificationMethod": "Strict topic-level classification; chapter-level weightage was excluded.",
    "disclaimer": "Historical frequency is a record of past papers and not a guarantee of future NEET paper contents."
  }
}
};