import { DetailedTopicContent } from '../../types/neet';

export const physAcRmsValuesDetails: DetailedTopicContent = {
  topicId: "phys-ac-rms-values",
  topicName: "AC Basics, RMS & Reactance (R, L, C Circuits)",
  subject: "Physics",
  class: "Class 12",
  classification: "Electromagnetic Induction & Alternating Current",
  chapter: "Alternating Current",

  whatIsThisTopic: "First-principles masterclass on Alternating Current: mathematical formulation of sinusoidal EMF and current, physical meaning and integral derivations of Mean and RMS values, behavior of pure resistive, inductive, and capacitive AC circuits, inductive/capacitive reactances, and rotating phasor representations.",

  basicIdea: [
    "Direct Current (DC) flows unidirectionally with constant magnitude, whereas Alternating Current (AC) periodically reverses its direction and varies continuously in magnitude with time according to sinusoidal harmonic functions.",
    "The average value of sinusoidal AC over a full cycle is mathematically ZERO due to equal and opposite half-cycles, requiring Root Mean Square (RMS) value based on the Joule heating effect (H = I_rms² R t) to quantify effective AC strength.",
    "In a pure resistor, current and voltage are strictly in phase (φ = 0°). In a pure inductor, self-induced back EMF causes current to lag voltage by 90° (π/2 rad) with inductive reactance X_L = ωL. In a pure capacitor, alternating charging-discharging dynamics cause current to lead voltage by 90° (π/2 rad) with capacitive reactance X_C = 1/(ωC)."
  ],

  importantTerms: [
    {
      term: "Alternating Current (AC)",
      symbol: "i(t)",
      definition: "An electric current whose magnitude changes continuously with time and whose direction reverses periodically at regular intervals, typically modeled as i(t) = I₀ sin(ωt + φ).",
      neetNote: "Household AC in India has a frequency of 50 Hz and RMS voltage of 220 V (peak voltage is ~311 V)."
    },
    {
      term: "Peak Value (Amplitude)",
      symbol: "I₀, V₀",
      definition: "The maximum instantaneous value attained by alternating current or voltage during one complete cycle in either the positive or negative direction.",
      neetNote: "AC measuring instruments do NOT read peak value; they measure RMS value."
    },
    {
      term: "Root Mean Square (RMS) Value",
      symbol: "I_rms, V_rms",
      definition: "The steady direct current (DC) that produces the exact same amount of Joule heat in a given resistor over a given time interval as is produced by the alternating current in the same resistor during the same time.",
      neetNote: "For sinusoidal AC: I_rms = I₀ / √2 ≈ 0.707 I₀; V_rms = V₀ / √2 ≈ 0.707 V₀."
    },
    {
      term: "Average (Mean) Value over Half-Cycle",
      symbol: "I_avg, V_avg",
      definition: "The steady DC current that transfers the same total electric charge through a circuit element as transferred by the AC during one half-cycle: I_avg = (2/π)I₀ ≈ 0.637 I₀.",
      neetNote: "Average over a full complete cycle is ALWAYS zero for symmetrical AC."
    },
    {
      term: "Inductive Reactance",
      symbol: "X_L",
      definition: "The effective opposition offered by an ideal inductor to the flow of alternating current, arising from self-induced back EMF: X_L = ωL = 2πfL (measured in Ohms, Ω).",
      neetNote: "For DC (f = 0), X_L = 0 (inductor acts as an ideal zero-resistance short circuit in steady state)."
    },
    {
      term: "Capacitive Reactance",
      symbol: "X_C",
      definition: "The effective opposition offered by an ideal capacitor to the flow of alternating current, governed by its cyclic electrostatic charge accumulation: X_C = 1/(ωC) = 1/(2πfC) (in Ω).",
      neetNote: "For DC (f = 0), X_C = ∞ (capacitor completely blocks steady DC)."
    },
    {
      term: "Phasor",
      symbol: "Vector V⃗, I⃗",
      definition: "A vector of length equal to peak amplitude that rotates counterclockwise about the origin with uniform angular velocity ω, whose projection on the vertical axis gives the instantaneous value.",
      neetNote: "Phasors convert differential calculus equations of AC into simple vector addition."
    }
  ],

  conceptExplanation: [
    {
      heading: "1. Chapter Introduction & The Conceptual Flow of AC",
      paragraphs: [
        "In Direct Current (DC) circuits, electric charge moves persistently in a single direction driven by a steady electrochemical potential. While DC is ideal for electronic chips and chemical electroplating, it suffers massive energy losses (I²R) when transported over hundreds of kilometers because DC voltages cannot be stepped up or down easily without complex electronic converters.",
        "Alternating Current (AC) solves this fundamental global challenge. Generated by rotating coils in uniform magnetic fields (Faraday's Law of Electromagnetic Induction), AC EMF varies sinusoidally: v(t) = V₀ sin(ωt). Because AC voltages can be elevated to hundreds of kilovolts using step-up transformers, transmission current is reduced proportionally, slashing transmission heat dissipation to negligible levels.",
        "When sinusoidal voltage is applied across circuit elements, the physical response depends entirely on the nature of the element: (1) Resistors dissipate energy directly into heat via electron-lattice collisions where current and voltage remain perfectly synchronized; (2) Inductors generate opposing Faraday back-EMF (-L di/dt), creating inertia that delays the current buildup; (3) Capacitors accumulate charge on plates (q = Cv), demanding maximum charge flow (current) when voltage is changing most rapidly.",
        "This fundamental difference gives rise to Phase Differences (φ), Reactances (X_L, X_C), and total Circuit Impedance (Z), culminating in the famous Series LCR Resonance and Transformer theory."
      ],
      visual: {
        type: 'svg',
        svgContent: `<svg viewBox="0 0 760 300" xmlns="http://www.w3.org/2000/svg" class="w-full h-auto max-w-2xl mx-auto">
          <defs>
            <marker id="ac-arrow" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
              <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#0284c7"/>
            </marker>
          </defs>
          <rect width="760" height="300" fill="#f8fafc" rx="14" stroke="#cbd5e1" stroke-width="1.5"/>
          <text x="380" y="28" fill="#0f172a" font-size="15" font-weight="bold" text-anchor="middle" letter-spacing="0.5">AC PHYSICS CONCEPT-FLOW ARCHITECTURE</text>
          
          <!-- Top Row Boxes -->
          <g transform="translate(30, 50)">
            <rect width="125" height="52" fill="#e0f2fe" stroke="#0284c7" stroke-width="1.5" rx="8"/>
            <text x="62.5" y="22" fill="#0369a1" font-size="11" font-weight="bold" text-anchor="middle">AC Voltage &amp; Current</text>
            <text x="62.5" y="38" fill="#075985" font-size="10" text-anchor="middle">v = V₀ sin(ωt)</text>
          </g>
          <line x1="155" y1="76" x2="190" y2="76" stroke="#0284c7" stroke-width="2" marker-end="url(#ac-arrow)"/>

          <g transform="translate(195, 50)">
            <rect width="125" height="52" fill="#fef3c7" stroke="#d97706" stroke-width="1.5" rx="8"/>
            <text x="62.5" y="22" fill="#b45309" font-size="11" font-weight="bold" text-anchor="middle">Mean &amp; RMS Values</text>
            <text x="62.5" y="38" fill="#92400e" font-size="10" text-anchor="middle">I_rms = I₀/√2 (Heating)</text>
          </g>
          <line x1="320" y1="76" x2="355" y2="76" stroke="#0284c7" stroke-width="2" marker-end="url(#ac-arrow)"/>

          <g transform="translate(360, 50)">
            <rect width="165" height="52" fill="#ede9fe" stroke="#7c3aed" stroke-width="1.5" rx="8"/>
            <text x="82.5" y="22" fill="#6d28d9" font-size="11" font-weight="bold" text-anchor="middle">Pure Components (R, L, C)</text>
            <text x="82.5" y="38" fill="#5b21b6" font-size="10" text-anchor="middle">X_L = ωL | X_C = 1/(ωC)</text>
          </g>
          <line x1="525" y1="76" x2="560" y2="76" stroke="#0284c7" stroke-width="2" marker-end="url(#ac-arrow)"/>

          <g transform="translate(565, 50)">
            <rect width="165" height="52" fill="#fee2e2" stroke="#dc2626" stroke-width="1.5" rx="8"/>
            <text x="82.5" y="22" fill="#b91c1c" font-size="11" font-weight="bold" text-anchor="middle">Phase Difference (φ)</text>
            <text x="82.5" y="38" fill="#991b1b" font-size="10" text-anchor="middle">R (0°) | L (+90°) | C (-90°)</text>
          </g>

          <!-- Connecting line down -->
          <path d="M 647 102 L 647 135 L 110 135 L 110 165" fill="none" stroke="#0284c7" stroke-width="2" marker-end="url(#ac-arrow)"/>

          <!-- Bottom Row Boxes -->
          <g transform="translate(30, 170)">
            <rect width="160" height="52" fill="#dcfce7" stroke="#16a34a" stroke-width="1.5" rx="8"/>
            <text x="80" y="22" fill="#15803d" font-size="11" font-weight="bold" text-anchor="middle">Series LCR Impedance</text>
            <text x="80" y="38" fill="#166534" font-size="10" text-anchor="middle">Z = √[R² + (X_L - X_C)²]</text>
          </g>
          <line x1="190" y1="196" x2="225" y2="196" stroke="#0284c7" stroke-width="2" marker-end="url(#ac-arrow)"/>

          <g transform="translate(230, 170)">
            <rect width="155" height="52" fill="#fef9c3" stroke="#ca8a04" stroke-width="1.5" rx="8"/>
            <text x="77.5" y="22" fill="#a16207" font-size="11" font-weight="bold" text-anchor="middle">LCR Resonance</text>
            <text x="77.5" y="38" fill="#854d0e" font-size="10" text-anchor="middle">f₀ = 1/(2π√LC), Z_min = R</text>
          </g>
          <line x1="385" y1="196" x2="420" y2="196" stroke="#0284c7" stroke-width="2" marker-end="url(#ac-arrow)"/>

          <g transform="translate(425, 170)">
            <rect width="150" height="52" fill="#ccfbf1" stroke="#0d9488" stroke-width="1.5" rx="8"/>
            <text x="75" y="22" fill="#0f766e" font-size="11" font-weight="bold" text-anchor="middle">AC Power &amp; Wattless</text>
            <text x="75" y="38" fill="#115e59" font-size="10" text-anchor="middle">P = V_rms I_rms cosφ</text>
          </g>
          <line x1="575" y1="196" x2="605" y2="196" stroke="#0284c7" stroke-width="2" marker-end="url(#ac-arrow)"/>

          <g transform="translate(610, 170)">
            <rect width="125" height="52" fill="#fae8ff" stroke="#c026d3" stroke-width="1.5" rx="8"/>
            <text x="62.5" y="22" fill="#a21caf" font-size="11" font-weight="bold" text-anchor="middle">Transformers</text>
            <text x="62.5" y="38" fill="#86198f" font-size="10" text-anchor="middle">V_s/V_p = N_s/N_p</text>
          </g>

          <rect x="50" y="246" width="660" height="36" fill="#f1f5f9" stroke="#94a3b8" stroke-dasharray="4 3" rx="6"/>
          <text x="380" y="268" fill="#475569" font-size="11.5" font-weight="500" text-anchor="middle">Core Foundation: Sinusoidal Driving Function → Element Differential Laws → Phasor Geometry → Practical Devices</text>
        </svg>`,
        caption: "Figure 7.1: Master Concept Flow of Alternating Current from first principles to industrial transformer applications.",
        guide: "Trace through each block sequentially to maintain structural clarity while solving complex NEET circuit problems."
      },
      importantPoints: [
        "Direct Current maintains constant direction; Alternating Current continuously varies and periodically inverts.",
        "AC is preferred for transmission because high voltages reduce I²R losses, enabled by high-efficiency transformers."
      ]
    },
    {
      heading: "2. Alternating Current & Voltage: The Mathematical Model",
      paragraphs: [
        "A sinusoidal alternating current is mathematically expressed as: i(t) = I₀ sin(ωt + φ₀) or i(t) = I₀ cos(ωt + φ₀), where i(t) represents instantaneous current at time t, I₀ is the peak amplitude, ω is the angular frequency (rad/s), and (ωt + φ₀) is the instantaneous phase angle.",
        "Key Fundamental Quantities:",
        "1. Peak Amplitude (I₀, V₀): The maximum displacement from the zero-baseline. Peak-to-peak amplitude is 2I₀ or 2V₀.",
        "2. Time Period (T): The time duration required for the wave to execute one complete cycle: T = 2π/ω = 1/f.",
        "3. Frequency (f): Number of cycles completed per second (Hz). In India, standard commercial supply has f = 50 Hz (T = 20 ms); in the USA, f = 60 Hz (T = 16.67 ms).",
        "4. Angular Frequency (ω): The rate of change of phase: ω = 2πf = 2π/T (rad/s). For 50 Hz supply, ω = 2π(50) = 100π ≈ 314.16 rad/s.",
        "5. Phase (θ = ωt + φ): The argument of the trigonometric sine function, determining the exact instantaneous state (direction and magnitude) of the alternating quantity."
      ],
      visual: {
        type: 'svg',
        svgContent: `<svg viewBox="0 0 720 320" xmlns="http://www.w3.org/2000/svg" class="w-full h-auto max-w-2xl mx-auto">
          <defs>
            <marker id="dim-arrow" viewBox="0 0 10 10" refX="5" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse">
              <path d="M 0 2 L 8 5 L 0 8 z" fill="#475569"/>
            </marker>
          </defs>
          <rect width="720" height="320" fill="#ffffff" rx="12" stroke="#cbd5e1" stroke-width="1.5"/>
          <text x="360" y="26" fill="#0f172a" font-size="14" font-weight="bold" text-anchor="middle">SINUSOIDAL AC WAVEFORM PARAMETERS: i(t) = I₀ sin(ωt)</text>
          
          <!-- Axes -->
          <line x1="60" y1="160" x2="680" y2="160" stroke="#334155" stroke-width="2"/>
          <line x1="100" y1="30" x2="100" y2="290" stroke="#334155" stroke-width="2"/>
          
          <!-- Axis Labels -->
          <text x="690" y="164" fill="#334155" font-size="12" font-weight="bold">Time (t) / Phase (ωt)</text>
          <text x="95" y="24" fill="#334155" font-size="12" font-weight="bold" text-anchor="end">Current i(t)</text>
          <text x="85" y="165" fill="#64748b" font-size="11" text-anchor="end">0</text>

          <!-- Sine Wave Path -->
          <!-- 1 full cycle from x=100 to x=540 (width 440). Half cycle at 320, peak at 210 (y=70), trough at 430 (y=250) -->
          <path d="M 100 160 Q 155 40 210 70 T 320 160 Q 375 280 430 250 T 540 160 Q 595 40 650 70" fill="none" stroke="#2563eb" stroke-width="3.5"/>

          <!-- Positive and Negative Halves shading -->
          <path d="M 100 160 Q 155 40 210 70 T 320 160 Z" fill="#3b82f6" fill-opacity="0.12"/>
          <path d="M 320 160 Q 375 280 430 250 T 540 160 Z" fill="#ef4444" fill-opacity="0.12"/>

          <!-- Zero Crossings -->
          <circle cx="100" cy="160" r="4.5" fill="#0f172a"/>
          <circle cx="320" cy="160" r="4.5" fill="#0f172a"/>
          <circle cx="540" cy="160" r="4.5" fill="#0f172a"/>
          <text x="320" y="180" fill="#0f172a" font-size="11" font-weight="bold" text-anchor="middle">t = T/2 (π rad)</text>
          <text x="540" y="180" fill="#0f172a" font-size="11" font-weight="bold" text-anchor="middle">t = T (2π rad)</text>
          <text x="210" y="180" fill="#64748b" font-size="10" text-anchor="middle">t = T/4</text>
          <text x="430" y="145" fill="#64748b" font-size="10" text-anchor="middle">t = 3T/4</text>

          <!-- Peak Amplitude I₀ Lines -->
          <line x1="100" y1="70" x2="210" y2="70" stroke="#2563eb" stroke-width="1.5" stroke-dasharray="4 3"/>
          <line x1="75" y1="160" x2="75" y2="70" stroke="#2563eb" stroke-width="1.5" marker-start="url(#dim-arrow)" marker-end="url(#dim-arrow)"/>
          <text x="70" y="115" fill="#2563eb" font-size="11" font-weight="bold" text-anchor="end">+I₀ (Peak)</text>

          <line x1="100" y1="250" x2="430" y2="250" stroke="#ef4444" stroke-width="1.5" stroke-dasharray="4 3"/>
          <line x1="75" y1="160" x2="75" y2="250" stroke="#ef4444" stroke-width="1.5" marker-start="url(#dim-arrow)" marker-end="url(#dim-arrow)"/>
          <text x="70" y="210" fill="#ef4444" font-size="11" font-weight="bold" text-anchor="end">-I₀ (Peak)</text>

          <!-- Period Dimension -->
          <line x1="100" y1="285" x2="540" y2="285" stroke="#475569" stroke-width="1.5" marker-start="url(#dim-arrow)" marker-end="url(#dim-arrow)"/>
          <text x="320" y="280" fill="#475569" font-size="11" font-weight="bold" text-anchor="middle">Complete Time Period (T = 1/f = 2π/ω)</text>

          <!-- Cycle labels -->
          <rect x="155" y="95" width="110" height="26" fill="#ffffff" stroke="#2563eb" rx="5"/>
          <text x="210" y="112" fill="#1d4ed8" font-size="10.5" font-weight="bold" text-anchor="middle">+ Half-Cycle</text>

          <rect x="375" y="200" width="110" height="26" fill="#ffffff" stroke="#ef4444" rx="5"/>
          <text x="430" y="217" fill="#b91c1c" font-size="10.5" font-weight="bold" text-anchor="middle">- Half-Cycle</text>
        </svg>`,
        caption: "Figure 7.2: Standard sinusoidal alternating current waveform illustrating peak amplitude (+I₀, -I₀), time period (T), zero-crossings, and half-cycles.",
        guide: "Notice that for every positive area element in the first half-cycle (0 to T/2), there is an identical negative area element in the second half-cycle (T/2 to T)."
      },
      importantPoints: [
        "In India: f = 50 Hz, ω = 100π rad/s ≈ 314.16 rad/s, T = 0.02 s = 20 ms.",
        "Zero-crossings occur at t = 0, T/2, T, 3T/2... and peak values occur at t = T/4, 3T/4, 5T/4..."
      ]
    },
    {
      heading: "3. Average (Mean) Value of AC: Full Cycle vs Half Cycle",
      paragraphs: [
        "The Average (Mean) value of any time-varying quantity i(t) over a time interval from t₁ to t₂ is defined as: I_avg = (1 / (t₂ - t₁)) ∫[t₁ to t₂] i(t) dt.",
        "1. Over a Complete Cycle (0 to T):",
        "I_full = (1/T) ∫[0 to T] I₀ sin(ωt) dt = (I₀/T) [ -cos(ωt)/ω ]₀^T = (-I₀ / (ωT)) [cos(ωT) - cos(0)]. Since ωT = (2π/T)T = 2π, cos(2π) = 1 and cos(0) = 1. Therefore: I_full = (-I₀ / 2π) [1 - 1] = 0.",
        "Physical Reason: The total electric charge transported in the positive direction during the positive half-cycle (+q) is exactly cancelled by the charge transported in the reverse direction during the negative half-cycle (-q). The net charge transferred over a full period is zero.",
        "2. Over a Positive Half-Cycle (0 to T/2):",
        "I_half = (1 / (T/2)) ∫[0 to T/2] I₀ sin(ωt) dt = (2I₀/T) [ -cos(ωt)/ω ]₀^(T/2) = (2I₀ / (ωT)) [ -cos(π) - (-cos 0) ] = (2I₀ / 2π) [ -(-1) + 1 ] = (2I₀ / π) [2] / 2 = 2I₀ / π.",
        "Numerical Values: I_avg(half) = (2/π) I₀ ≈ 0.6366 I₀ ≈ 63.7% of peak value. Similarly, V_avg(half) = (2/π) V₀ ≈ 0.637 V₀."
      ],
      visual: {
        type: 'svg',
        svgContent: `<svg viewBox="0 0 700 250" xmlns="http://www.w3.org/2000/svg" class="w-full h-auto max-w-xl mx-auto">
          <rect width="700" height="250" fill="#f8fafc" rx="12" stroke="#cbd5e1" stroke-width="1.5"/>
          <text x="350" y="24" fill="#0f172a" font-size="13" font-weight="bold" text-anchor="middle">CHARGE INTEGRATION &amp; AVERAGE AC (HALF VS FULL CYCLE)</text>
          
          <line x1="50" y1="130" x2="650" y2="130" stroke="#475569" stroke-width="2"/>
          <line x1="90" y1="30" x2="90" y2="230" stroke="#475569" stroke-width="2"/>

          <!-- Waveform 1 cycle -->
          <path d="M 90 130 Q 180 30 270 130 T 450 130" fill="none" stroke="#2563eb" stroke-width="3"/>
          <path d="M 90 130 Q 180 30 270 130 Z" fill="#3b82f6" fill-opacity="0.2"/>
          <path d="M 270 130 Q 360 230 450 130 Z" fill="#ef4444" fill-opacity="0.2"/>

          <text x="180" y="105" fill="#1e40af" font-size="12" font-weight="bold" text-anchor="middle">Charge +q</text>
          <text x="360" y="165" fill="#991b1b" font-size="12" font-weight="bold" text-anchor="middle">Charge -q</text>

          <!-- Average level for half cycle -->
          <line x1="90" y1="79" x2="270" y2="79" stroke="#d97706" stroke-width="2" stroke-dasharray="5 3"/>
          <text x="280" y="83" fill="#b45309" font-size="11" font-weight="bold">I_avg = (2/π)I₀ ≈ 0.637 I₀</text>

          <!-- Net full cycle line -->
          <line x1="90" y1="130" x2="450" y2="130" stroke="#16a34a" stroke-width="4" stroke-opacity="0.6"/>
          <text x="460" y="134" fill="#15803d" font-size="11" font-weight="bold">Net Full Cycle Average = 0</text>
          
          <rect x="470" y="45" width="210" height="60" fill="#ffffff" stroke="#cbd5e1" rx="6"/>
          <text x="480" y="65" fill="#0f172a" font-size="10.5" font-weight="bold">NEET Trap Alert:</text>
          <text x="480" y="80" fill="#475569" font-size="10">DC ammeter reads zero when</text>
          <text x="480" y="94" fill="#475569" font-size="10">connected to AC supply!</text>
        </svg>`,
        caption: "Figure 7.3: Graphical demonstration showing why full-cycle mean AC is zero (+q cancels -q) whereas half-cycle average equals 2I₀/π.",
        guide: "Remember: Moving-coil galvanometers and standard DC meters work on magnetic torque proportional to average current, so they read zero in AC circuits."
      },
      importantPoints: [
        "Full cycle average = 0 (charge transferred = 0).",
        "Half cycle average = (2/π) I₀ ≈ 0.637 I₀ (only valid for symmetrical sine waves)."
      ]
    },
    {
      heading: "4. Root Mean Square (RMS) Value: First-Principles Derivation",
      paragraphs: [
        "Why do we need RMS value? Since average current over a full cycle is zero, average value cannot be used to quantify the work capacity or power delivery of AC. However, when AC passes through a resistor, heat is generated regardless of current direction because Joule heating depends on current squared: dH = i² R dt.",
        "Physical Definition: The RMS (or effective / virtual) value of AC is defined as that value of steady DC current which produces the same heating effect in a given resistor in a given time as is produced by the AC flowing through the same resistor for the same time.",
        "Mathematical Derivation for Sinusoidal Current i = I₀ sin(ωt):",
        "Heat produced by AC in one complete cycle (0 to T): H_AC = ∫[0 to T] i² R dt = R I₀² ∫[0 to T] sin²(ωt) dt.",
        "Using the trigonometric identity sin²θ = (1 - cos 2θ) / 2:",
        "H_AC = (R I₀² / 2) ∫[0 to T] (1 - cos 2ωt) dt = (R I₀² / 2) [ t - sin(2ωt)/(2ω) ]₀^T.",
        "Since sin(2ωT) = sin(4π) = 0 and sin(0) = 0, the integral simply evaluates to T:",
        "H_AC = (R I₀² / 2) · T = (I₀² / 2) R T.",
        "Heat produced by an equivalent steady DC current (I_rms) in the same resistor over time T: H_DC = I_rms² R T.",
        "Equating H_DC = H_AC:",
        "I_rms² R T = (I₀² / 2) R T  ===>  I_rms = √(I₀² / 2) = I₀ / √2.",
        "Numerical Values: I_rms = I₀ / √2 ≈ 0.7071 I₀ (70.7% of peak). Similarly, V_rms = V₀ / √2 ≈ 0.7071 V₀.",
        "Practical Significance: Domestic mains voltage in India is specified as 220 V. This is an RMS rating! The actual peak voltage experienced twice per cycle is V₀ = V_rms × √2 = 220 × 1.414 = 311.13 V. Peak-to-peak voltage swing is 2V₀ = 622.3 V. Hence, 220 V AC is significantly more dangerous than 220 V DC because peak AC reaches 311 V."
      ],
      visual: {
        type: 'svg',
        svgContent: `<svg viewBox="0 0 740 300" xmlns="http://www.w3.org/2000/svg" class="w-full h-auto max-w-2xl mx-auto">
          <rect width="740" height="300" fill="#ffffff" rx="12" stroke="#cbd5e1" stroke-width="1.5"/>
          <text x="370" y="24" fill="#0f172a" font-size="14" font-weight="bold" text-anchor="middle">PEAK (I₀) vs RMS (I_rms) vs AVERAGE (I_avg) COMPARISON</text>
          
          <line x1="60" y1="160" x2="680" y2="160" stroke="#334155" stroke-width="2"/>
          <line x1="100" y1="30" x2="100" y2="280" stroke="#334155" stroke-width="2"/>

          <!-- Waveform -->
          <path d="M 100 160 Q 185 30 270 160 T 440 160 T 610 160" fill="none" stroke="#64748b" stroke-width="2.5"/>

          <!-- Peak Line (y=50) -->
          <line x1="100" y1="50" x2="610" y2="50" stroke="#ef4444" stroke-width="2" stroke-dasharray="6 3"/>
          <circle cx="185" cy="50" r="4.5" fill="#ef4444"/>
          <text x="620" y="54" fill="#ef4444" font-size="12" font-weight="bold">Peak I₀ = 1.000 (100%)</text>

          <!-- RMS Line (y=160 - 110*0.707 = 82) -->
          <line x1="100" y1="82" x2="610" y2="82" stroke="#2563eb" stroke-width="2.5"/>
          <text x="620" y="86" fill="#2563eb" font-size="12" font-weight="bold">RMS I_rms = I₀/√2 ≈ 0.707 I₀ (Heating)</text>

          <!-- Average Half Cycle Line (y=160 - 110*0.637 = 90) -->
          <line x1="100" y1="90" x2="610" y2="90" stroke="#d97706" stroke-width="2" stroke-dasharray="4 3"/>
          <text x="620" y="105" fill="#d97706" font-size="11" font-weight="bold">Half-Cycle Avg I_avg = (2/π)I₀ ≈ 0.637 I₀</text>

          <!-- Highlight Comparison Box -->
          <g transform="translate(120, 185)">
            <rect width="480" height="90" fill="#f8fafc" stroke="#94a3b8" rx="8"/>
            <text x="240" y="22" fill="#0f172a" font-size="12" font-weight="bold" text-anchor="middle">KEY RELATIONSHIP HIERARCHY (FOR SINE WAVE)</text>
            <text x="240" y="44" fill="#1e293b" font-size="13" font-weight="bold" text-anchor="middle">I₀ (1.414 I_rms)  &gt;  I_rms (0.707 I₀)  &gt;  I_avg(half) (0.637 I₀)</text>
            <text x="240" y="68" fill="#475569" font-size="11" text-anchor="middle">Form Factor = I_rms / I_avg = (I₀/√2) / (2I₀/π) = π / (2√2) ≈ 1.11</text>
          </g>
        </svg>`,
        caption: "Figure 7.4: Comparative amplitude levels of Peak, RMS, and Half-Cycle Mean values for a sinusoidal waveform.",
        guide: "Remember: Form Factor = RMS / Average = 1.11; Peak Factor (Crest Factor) = Peak / RMS = √2 ≈ 1.414."
      },
      importantPoints: [
        "All AC meters (hot-wire ammeters, digital multimeters, moving-iron meters) calibrate and display RMS values.",
        "Heating power depends strictly on RMS: P = I_rms² R = V_rms² / R."
      ]
    },
    {
      heading: "5. AC Through a Pure Resistor: Zero Phase Difference",
      paragraphs: [
        "Consider a pure resistor of resistance R connected across an alternating voltage source: v(t) = V₀ sin(ωt).",
        "Applying Ohm's law at any instant t: i(t) = v(t) / R = (V₀ / R) sin(ωt) = I₀ sin(ωt), where I₀ = V₀ / R.",
        "Key Deductions:",
        "1. Phase Relationship: The phase angle of voltage is ωt, and the phase angle of current is ωt. The phase difference φ = 0°. Current and voltage are strictly IN PHASE.",
        "2. Maximum and Zero Points: When voltage is zero, current is simultaneously zero. When voltage hits its peak (+V₀), current simultaneously hits its peak (+I₀).",
        "3. RMS Relationship: I_rms = V_rms / R.",
        "4. Power Dissipation: Instantaneous power p(t) = v(t)i(t) = V₀I₀ sin²(ωt). Average power over a complete cycle: P = V₀I₀ (1/2) = (V₀/√2)(I₀/√2) = V_rms I_rms = I_rms² R = V_rms² / R.",
        "All electrical energy supplied by the source is irreversibly converted into thermal energy."
      ],
      visual: {
        type: 'svg',
        svgContent: `<svg viewBox="0 0 740 280" xmlns="http://www.w3.org/2000/svg" class="w-full h-auto max-w-2xl mx-auto">
          <rect width="740" height="280" fill="#f8fafc" rx="12" stroke="#cbd5e1" stroke-width="1.5"/>
          <text x="370" y="24" fill="#0f172a" font-size="13.5" font-weight="bold" text-anchor="middle">PURE RESISTOR IN AC: CIRCUIT, WAVEFORMS &amp; PHASOR (φ = 0°)</text>
          
          <!-- Circuit on Left -->
          <g transform="translate(40, 50)">
            <rect width="180" height="190" fill="#ffffff" stroke="#cbd5e1" rx="8"/>
            <text x="90" y="24" fill="#0f172a" font-size="12" font-weight="bold" text-anchor="middle">Circuit Diagram</text>
            
            <!-- AC Source -->
            <circle cx="45" cy="110" r="18" fill="#e0f2fe" stroke="#0284c7" stroke-width="2"/>
            <path d="M 38 110 Q 41.5 103 45 110 T 52 110" fill="none" stroke="#0284c7" stroke-width="2"/>
            <text x="45" y="145" fill="#0369a1" font-size="10" text-anchor="middle">v = V₀ sinωt</text>
            
            <!-- Resistor -->
            <path d="M 135 60 L 135 90 L 128 95 L 142 102 L 128 109 L 142 116 L 128 123 L 142 130 L 135 135 L 135 165" fill="none" stroke="#dc2626" stroke-width="2.5"/>
            <text x="155" y="115" fill="#dc2626" font-size="12" font-weight="bold">R</text>

            <!-- Connecting Wires -->
            <line x1="45" y1="92" x2="45" y2="60" stroke="#334155" stroke-width="2"/>
            <line x1="45" y1="60" x2="135" y2="60" stroke="#334155" stroke-width="2"/>
            <line x1="45" y1="128" x2="45" y2="165" stroke="#334155" stroke-width="2"/>
            <line x1="45" y1="165" x2="135" y2="165" stroke="#334155" stroke-width="2"/>
          </g>

          <!-- Waveforms in Center -->
          <g transform="translate(240, 50)">
            <rect width="270" height="190" fill="#ffffff" stroke="#cbd5e1" rx="8"/>
            <text x="135" y="24" fill="#0f172a" font-size="12" font-weight="bold" text-anchor="middle">Waveforms (In Phase)</text>
            
            <line x1="20" y1="110" x2="250" y2="110" stroke="#475569" stroke-width="1.5"/>
            <line x1="30" y1="40" x2="30" y2="175" stroke="#475569" stroke-width="1.5"/>

            <!-- Voltage Wave (Blue) -->
            <path d="M 30 110 Q 80 40 130 110 T 230 110" fill="none" stroke="#2563eb" stroke-width="2.5"/>
            <!-- Current Wave (Red, smaller amplitude) -->
            <path d="M 30 110 Q 80 65 130 110 T 230 110" fill="none" stroke="#dc2626" stroke-width="2" stroke-dasharray="4 2"/>

            <text x="80" y="38" fill="#2563eb" font-size="10.5" font-weight="bold">v(t) = V₀ sinωt</text>
            <text x="80" y="60" fill="#dc2626" font-size="10" font-weight="bold">i(t) = I₀ sinωt</text>
            <text x="135" y="180" fill="#16a34a" font-size="10.5" font-weight="bold" text-anchor="middle">Phase Difference φ = 0°</text>
          </g>

          <!-- Phasor on Right -->
          <g transform="translate(530, 50)">
            <rect width="170" height="190" fill="#ffffff" stroke="#cbd5e1" rx="8"/>
            <text x="85" y="24" fill="#0f172a" font-size="12" font-weight="bold" text-anchor="middle">Phasor Diagram</text>
            
            <circle cx="85" cy="110" r="5" fill="#475569"/>
            <!-- V Phasor -->
            <line x1="85" y1="110" x2="145" y2="70" stroke="#2563eb" stroke-width="3" marker-end="url(#dim-arrow)"/>
            <text x="150" y="68" fill="#2563eb" font-size="11" font-weight="bold">V⃗₀</text>

            <!-- I Phasor (collinear, shorter) -->
            <line x1="85" y1="110" x2="125" y2="83" stroke="#dc2626" stroke-width="2.5"/>
            <text x="110" y="75" fill="#dc2626" font-size="11" font-weight="bold">I⃗₀</text>

            <path d="M 115 110 A 30 30 0 0 0 110 93" fill="none" stroke="#475569" stroke-width="1.5"/>
            <text x="120" y="105" fill="#475569" font-size="10">ωt</text>
            <text x="85" y="165" fill="#1e293b" font-size="10.5" font-weight="bold" text-anchor="middle">Parallel / Collinear</text>
          </g>
        </svg>`,
        caption: "Figure 7.5: Pure resistive AC circuit showing concurrent zero-crossings and peaks (φ = 0°) in waveform and parallel phasor vectors.",
        guide: "Power dissipated in a resistor is strictly positive at all times (except at isolated zeros), meaning the resistor always absorbs energy from the AC supply."
      },
      importantPoints: [
        "In a pure resistor: φ = 0, power factor cosφ = 1 (unity).",
        "Average power = V_rms I_rms = I_rms² R."
      ]
    },
    {
      heading: "6. AC Through a Pure Inductor: 90° Phase Lag & Inductive Reactance",
      paragraphs: [
        "Consider an ideal inductor of self-inductance L with zero internal ohmic resistance (R = 0) connected to an AC source: v(t) = V₀ sin(ωt).",
        "As current attempts to change, the inductor develops a self-induced back-EMF according to Faraday-Lenz law: e = -L (di/dt).",
        "Applying Kirchhoff's loop rule to the circuit: v(t) + e = 0  ===>  V₀ sin(ωt) - L (di/dt) = 0.",
        "Rearranging: di = (V₀ / L) sin(ωt) dt.",
        "Integrating both sides with respect to time:",
        "i(t) = (V₀ / L) ∫ sin(ωt) dt = -(V₀ / ωL) cos(ωt).",
        "Using the trigonometric identity -cos(θ) = sin(θ - π/2):",
        "i(t) = (V₀ / ωL) sin(ωt - π/2) = I₀ sin(ωt - π/2).",
        "Key Physical Insights:",
        "1. Phase Relationship: The phase of voltage is ωt, while the phase of current is (ωt - π/2). Therefore, CURRENT LAGS VOLTAGE BY 90° (π/2 rad), or equivalently, VOLTAGE LEADS CURRENT BY 90°.",
        "2. Inductive Reactance (X_L): The quantity X_L = ωL = 2πfL acts as the effective opposition offered by the inductor. It has SI units of Ohms (Ω).",
        "Peak Current: I₀ = V₀ / X_L; RMS Current: I_rms = V_rms / X_L = V_rms / (ωL).",
        "3. Physical Mechanism of Delay: The magnetic flux opposition (Faraday inertia) fights against the rise of current. When voltage peaks at t = 0, di/dt is maximum but i itself is zero. Current only peaks a quarter-cycle later (t = T/4)!"
      ],
      visual: {
        type: 'svg',
        svgContent: `<svg viewBox="0 0 740 290" xmlns="http://www.w3.org/2000/svg" class="w-full h-auto max-w-2xl mx-auto">
          <rect width="740" height="290" fill="#ffffff" rx="12" stroke="#cbd5e1" stroke-width="1.5"/>
          <text x="370" y="24" fill="#0f172a" font-size="13.5" font-weight="bold" text-anchor="middle">PURE INDUCTOR IN AC: CIRCUIT, WAVEFORMS &amp; PHASOR (CURRENT LAGS BY 90°)</text>
          
          <!-- Circuit on Left -->
          <g transform="translate(30, 50)">
            <rect width="180" height="200" fill="#f8fafc" stroke="#cbd5e1" rx="8"/>
            <text x="90" y="22" fill="#0f172a" font-size="11.5" font-weight="bold" text-anchor="middle">Pure Inductor Circuit</text>
            
            <circle cx="45" cy="115" r="16" fill="#e0f2fe" stroke="#0284c7" stroke-width="2"/>
            <path d="M 39 115 Q 42 109 45 115 T 51 115" fill="none" stroke="#0284c7" stroke-width="2"/>
            <text x="45" y="148" fill="#0369a1" font-size="9.5" text-anchor="middle">v = V₀ sinωt</text>
            
            <!-- Inductor Coils -->
            <path d="M 135 65 L 135 85 C 150 85 150 100 135 100 C 150 100 150 115 135 115 C 150 115 150 130 135 130 C 150 130 150 145 135 145 L 135 165" fill="none" stroke="#7c3aed" stroke-width="2.5"/>
            <text x="155" y="120" fill="#7c3aed" font-size="12" font-weight="bold">L</text>

            <line x1="45" y1="99" x2="45" y2="65" stroke="#334155" stroke-width="2"/>
            <line x1="45" y1="65" x2="135" y2="65" stroke="#334155" stroke-width="2"/>
            <line x1="45" y1="131" x2="45" y2="165" stroke="#334155" stroke-width="2"/>
            <line x1="45" y1="165" x2="135" y2="165" stroke="#334155" stroke-width="2"/>
          </g>

          <!-- Waveforms in Center -->
          <g transform="translate(230, 50)">
            <rect width="280" height="200" fill="#f8fafc" stroke="#cbd5e1" rx="8"/>
            <text x="140" y="22" fill="#0f172a" font-size="11.5" font-weight="bold" text-anchor="middle">Waveforms (90° Phase Shift)</text>
            
            <line x1="20" y1="115" x2="260" y2="115" stroke="#475569" stroke-width="1.5"/>
            <line x1="40" y1="40" x2="40" y2="185" stroke="#475569" stroke-width="1.5"/>

            <!-- Voltage Wave: starts at 0 going up -->
            <path d="M 40 115 Q 90 45 140 115 T 240 115" fill="none" stroke="#2563eb" stroke-width="2.5"/>
            <!-- Current Wave: starts at -I₀ at t=0 -->
            <path d="M 40 185 Q 90 185 140 115 T 240 115" fill="none" stroke="#7c3aed" stroke-width="2.5" stroke-dasharray="5 3"/>

            <text x="90" y="42" fill="#2563eb" font-size="10.5" font-weight="bold">v = V₀ sin(ωt)</text>
            <text x="145" y="180" fill="#7c3aed" font-size="10" font-weight="bold">i = I₀ sin(ωt - π/2)</text>
            <text x="140" y="196" fill="#b91c1c" font-size="10.5" font-weight="bold" text-anchor="middle">Current reaches peak T/4 LATER</text>
          </g>

          <!-- Phasor on Right -->
          <g transform="translate(530, 50)">
            <rect width="180" height="200" fill="#f8fafc" stroke="#cbd5e1" rx="8"/>
            <text x="90" y="22" fill="#0f172a" font-size="11.5" font-weight="bold" text-anchor="middle">Phasor Diagram</text>
            
            <circle cx="70" cy="130" r="4.5" fill="#475569"/>
            
            <!-- V Phasor (leads by 90°) -->
            <line x1="70" y1="130" x2="135" y2="65" stroke="#2563eb" stroke-width="3" marker-end="url(#dim-arrow)"/>
            <text x="142" y="65" fill="#2563eb" font-size="11" font-weight="bold">V⃗_L (Leads)</text>

            <!-- I Phasor (along reference/lags by 90°) -->
            <line x1="70" y1="130" x2="135" y2="155" stroke="#7c3aed" stroke-width="2.5" marker-end="url(#dim-arrow)"/>
            <text x="140" y="165" fill="#7c3aed" font-size="11" font-weight="bold">I⃗ (Lags)</text>

            <!-- 90 degree arc -->
            <path d="M 102 98 A 45 45 0 0 1 105 142" fill="none" stroke="#dc2626" stroke-width="2"/>
            <text x="115" y="120" fill="#dc2626" font-size="11" font-weight="bold">90°</text>
          </g>
        </svg>`,
        caption: "Figure 7.6: Pure inductive AC circuit showing current lagging voltage by π/2 (90°) due to Faraday back-EMF.",
        guide: "NEET Memory Rule: In Inductor L, Voltage V leads Current I. Remember mnemonic 'V-I-L' or 'ELI'."
      },
      importantPoints: [
        "X_L = 2πfL (proportional to frequency). As f increases, X_L increases linearly.",
        "For steady DC (f = 0), X_L = 0 Ω. An inductor offers zero opposition to steady DC."
      ]
    },
    {
      heading: "7. AC Through a Pure Capacitor: 90° Phase Lead & Capacitive Reactance",
      paragraphs: [
        "Consider an ideal capacitor of capacitance C connected across an AC voltage source: v(t) = V₀ sin(ωt).",
        "At any instant t, the electric charge stored on the plates is: q(t) = C v(t) = C V₀ sin(ωt).",
        "The instantaneous electric current flowing in the circuit is the rate of flow of charge:",
        "i(t) = dq / dt = (d/dt) [ C V₀ sin(ωt) ] = C V₀ ω cos(ωt).",
        "Using the trigonometric identity cos(θ) = sin(θ + π/2):",
        "i(t) = (ω C V₀) sin(ωt + π/2) = (V₀ / (1/ωC)) sin(ωt + π/2) = I₀ sin(ωt + π/2).",
        "Key Physical Insights:",
        "1. Phase Relationship: The phase of voltage is ωt, while the phase of current is (ωt + π/2). Therefore, CURRENT LEADS VOLTAGE BY 90° (π/2 rad), or equivalently, VOLTAGE LAGS CURRENT BY 90°.",
        "2. Capacitive Reactance (X_C): The effective opposition offered by the capacitor is X_C = 1 / (ωC) = 1 / (2πfC) (measured in Ω).",
        "Peak Current: I₀ = V₀ / X_C; RMS Current: I_rms = V_rms / X_C = V_rms · (2πfC).",
        "3. Physical Mechanism of Current Lead: Electric charges flow onto the capacitor plates most furiously when the voltage is passing through zero (maximum rate of change dv/dt). When voltage reaches its maximum, the plates are fully charged, and current momentarily ceases (i = 0)."
      ],
      visual: {
        type: 'svg',
        svgContent: `<svg viewBox="0 0 740 290" xmlns="http://www.w3.org/2000/svg" class="w-full h-auto max-w-2xl mx-auto">
          <rect width="740" height="290" fill="#ffffff" rx="12" stroke="#cbd5e1" stroke-width="1.5"/>
          <text x="370" y="24" fill="#0f172a" font-size="13.5" font-weight="bold" text-anchor="middle">PURE CAPACITOR IN AC: CIRCUIT, WAVEFORMS &amp; PHASOR (CURRENT LEADS BY 90°)</text>
          
          <!-- Circuit on Left -->
          <g transform="translate(30, 50)">
            <rect width="180" height="200" fill="#f8fafc" stroke="#cbd5e1" rx="8"/>
            <text x="90" y="22" fill="#0f172a" font-size="11.5" font-weight="bold" text-anchor="middle">Pure Capacitor Circuit</text>
            
            <circle cx="45" cy="115" r="16" fill="#e0f2fe" stroke="#0284c7" stroke-width="2"/>
            <path d="M 39 115 Q 42 109 45 115 T 51 115" fill="none" stroke="#0284c7" stroke-width="2"/>
            <text x="45" y="148" fill="#0369a1" font-size="9.5" text-anchor="middle">v = V₀ sinωt</text>
            
            <!-- Capacitor Parallel Plates -->
            <line x1="120" y1="95" x2="150" y2="95" stroke="#0d9488" stroke-width="3.5"/>
            <line x1="120" y1="135" x2="150" y2="135" stroke="#0d9488" stroke-width="3.5"/>
            <text x="160" y="120" fill="#0d9488" font-size="12" font-weight="bold">C</text>

            <line x1="45" y1="99" x2="45" y2="65" stroke="#334155" stroke-width="2"/>
            <line x1="45" y1="65" x2="135" y2="65" stroke="#334155" stroke-width="2"/>
            <line x1="135" y1="65" x2="135" y2="95" stroke="#334155" stroke-width="2"/>
            
            <line x1="45" y1="131" x2="45" y2="165" stroke="#334155" stroke-width="2"/>
            <line x1="45" y1="165" x2="135" y2="165" stroke="#334155" stroke-width="2"/>
            <line x1="135" y1="165" x2="135" y2="135" stroke="#334155" stroke-width="2"/>
          </g>

          <!-- Waveforms in Center -->
          <g transform="translate(230, 50)">
            <rect width="280" height="200" fill="#f8fafc" stroke="#cbd5e1" rx="8"/>
            <text x="140" y="22" fill="#0f172a" font-size="11.5" font-weight="bold" text-anchor="middle">Waveforms (Current Leads)</text>
            
            <line x1="20" y1="115" x2="260" y2="115" stroke="#475569" stroke-width="1.5"/>
            <line x1="40" y1="40" x2="40" y2="185" stroke="#475569" stroke-width="1.5"/>

            <!-- Voltage Wave: starts at 0 -->
            <path d="M 40 115 Q 90 45 140 115 T 240 115" fill="none" stroke="#2563eb" stroke-width="2.5"/>
            <!-- Current Wave: starts at +I₀ at t=0 -->
            <path d="M 40 45 Q 90 45 140 115 T 240 115" fill="none" stroke="#0d9488" stroke-width="2.5" stroke-dasharray="5 3"/>

            <text x="90" y="165" fill="#2563eb" font-size="10.5" font-weight="bold">v = V₀ sin(ωt)</text>
            <text x="90" y="38" fill="#0d9488" font-size="10" font-weight="bold">i = I₀ sin(ωt + π/2)</text>
            <text x="140" y="196" fill="#0d9488" font-size="10.5" font-weight="bold" text-anchor="middle">Current reaches peak T/4 EARLIER</text>
          </g>

          <!-- Phasor on Right -->
          <g transform="translate(530, 50)">
            <rect width="180" height="200" fill="#f8fafc" stroke="#cbd5e1" rx="8"/>
            <text x="90" y="22" fill="#0f172a" font-size="11.5" font-weight="bold" text-anchor="middle">Phasor Diagram</text>
            
            <circle cx="70" cy="130" r="4.5" fill="#475569"/>
            
            <!-- I Phasor (leads by 90°) -->
            <line x1="70" y1="130" x2="135" y2="65" stroke="#0d9488" stroke-width="3" marker-end="url(#dim-arrow)"/>
            <text x="142" y="65" fill="#0d9488" font-size="11" font-weight="bold">I⃗ (Leads)</text>

            <!-- V Phasor (lags by 90°) -->
            <line x1="70" y1="130" x2="135" y2="155" stroke="#2563eb" stroke-width="2.5" marker-end="url(#dim-arrow)"/>
            <text x="140" y="165" fill="#2563eb" font-size="11" font-weight="bold">V⃗_C (Lags)</text>

            <!-- 90 degree arc -->
            <path d="M 102 98 A 45 45 0 0 1 105 142" fill="none" stroke="#dc2626" stroke-width="2"/>
            <text x="115" y="120" fill="#dc2626" font-size="11" font-weight="bold">90°</text>
          </g>
        </svg>`,
        caption: "Figure 7.7: Pure capacitive AC circuit showing current leading voltage by π/2 (90°) due to plate charge dynamics.",
        guide: "NEET Memory Rule: In Capacitor C, Current I leads Voltage V. Remember mnemonic 'C-I-V' or 'ICE'."
      },
      importantPoints: [
        "X_C = 1 / (2πfC) (inversely proportional to frequency). As f increases, X_C drops to zero (capacitor acts as short circuit for high frequencies).",
        "For steady DC (f = 0), X_C = 1/0 = ∞. A capacitor completely blocks steady DC current."
      ]
    },
    {
      heading: "8. Comparative Reactance Dynamics & Frequency Dependence",
      paragraphs: [
        "Reactance represents the reactive opposition to AC flow without dissipative resistance losses.",
        "1. Inductive Reactance (X_L = 2πfL):",
        "Graph of X_L versus frequency f is a straight line passing through the origin (slope = 2πL). At zero frequency (DC), X_L = 0. Inductors easily pass DC but block ultra-high frequency AC.",
        "2. Capacitive Reactance (X_C = 1 / (2πfC)):",
        "Graph of X_C versus frequency f is a rectangular hyperbola (X_C · f = constant). At zero frequency (DC), X_C = ∞. Capacitors block steady DC but allow high-frequency signals to bypass effortlessly.",
        "3. Intersecting Frequency (Resonance): The specific frequency where X_L = X_C defines the series resonant frequency f₀ = 1 / (2π√(LC))."
      ],
      visual: {
        type: 'svg',
        svgContent: `<svg viewBox="0 0 700 280" xmlns="http://www.w3.org/2000/svg" class="w-full h-auto max-w-xl mx-auto">
          <rect width="700" height="280" fill="#f8fafc" rx="12" stroke="#cbd5e1" stroke-width="1.5"/>
          <text x="350" y="24" fill="#0f172a" font-size="13.5" font-weight="bold" text-anchor="middle">REACTANCE vs FREQUENCY CHARACTERISTICS (X_L vs X_C)</text>
          
          <line x1="80" y1="230" x2="620" y2="230" stroke="#334155" stroke-width="2"/>
          <line x1="100" y1="40" x2="100" y2="240" stroke="#334155" stroke-width="2"/>
          
          <text x="630" y="234" fill="#334155" font-size="12" font-weight="bold">Frequency (f)</text>
          <text x="95" y="35" fill="#334155" font-size="12" font-weight="bold" text-anchor="end">Reactance (Ω)</text>

          <!-- X_L line (Straight line through origin) -->
          <line x1="100" y1="230" x2="550" y2="60" stroke="#7c3aed" stroke-width="3"/>
          <text x="560" y="65" fill="#7c3aed" font-size="12" font-weight="bold">X_L = 2πfL (Linear)</text>

          <!-- X_C curve (Rectangular hyperbola) -->
          <path d="M 120 50 Q 150 180 300 200 T 580 225" fill="none" stroke="#0d9488" stroke-width="3"/>
          <text x="500" y="210" fill="#0d9488" font-size="12" font-weight="bold">X_C = 1/(2πfC) (Hyperbolic)</text>

          <!-- Resonant Intersection Point -->
          <!-- Intersection around x=280, y=160 -->
          <circle cx="270" cy="166" r="6" fill="#dc2626"/>
          <line x1="270" y1="166" x2="270" y2="230" stroke="#dc2626" stroke-width="1.5" stroke-dasharray="4 3"/>
          <line x1="100" y1="166" x2="270" y2="166" stroke="#dc2626" stroke-width="1.5" stroke-dasharray="4 3"/>
          <text x="270" y="248" fill="#dc2626" font-size="11" font-weight="bold" text-anchor="middle">f₀ = 1/(2π√LC)</text>
          <text x="60" y="170" fill="#dc2626" font-size="10.5" font-weight="bold">X_L = X_C</text>
        </svg>`,
        caption: "Figure 7.8: Frequency dependence of Inductive Reactance (linear growth) and Capacitive Reactance (hyperbolic decay) intersecting at resonance frequency f₀.",
        guide: "At low frequencies (f < f₀), X_C dominates and the circuit is capacitive; at high frequencies (f > f₀), X_L dominates and the circuit is inductive."
      },
      importantPoints: [
        "Resistance R is independent of frequency (horizontal line).",
        "Reactance and Resistance share the unit Ohm (Ω) but have fundamentally different physical meanings: Resistance dissipates real power, while Reactance only stores/returns energy."
      ]
    },
    {
      heading: "9. Phasor Theory & Phase Angle Master Summary",
      paragraphs: [
        "A Phasor is a graphical tool representing sinusoidally oscillating quantities as rotating two-dimensional vectors.",
        "Mathematical rules for Phasors:",
        "1. Length of phasor vector equals Peak Value (V₀ or I₀) or RMS Value (V_rms or I_rms).",
        "2. Phasor rotates counter-clockwise (CCW) with uniform angular velocity ω.",
        "3. Projection on the vertical y-axis at time t yields the instantaneous value: v(t) = V₀ sin(ωt).",
        "4. The angle between the voltage phasor and the current phasor is the Phase Angle (φ).",
        "Universal Memory Mnemonics:",
        "• 'CIVIL': In Capacitor (C), Current (I) leads Voltage (V); then Voltage (V) leads Current (I) in Inductor (L).",
        "• 'ELI the ICE man': E (voltage) Leads I in L (Inductor); I leads E (voltage) in C (Capacitor)."
      ],
      importantPoints: [
        "Pure R: φ = 0° (in phase).",
        "Pure L: φ = +90° (V leads I by π/2).",
        "Pure C: φ = -90° (I leads V by π/2)."
      ]
    }
  ],

  formulae: [
    {
      title: "Instantaneous AC Current & Voltage",
      formula: "i(t) = I₀ \\sin(\\omega t + \\phi), \\quad v(t) = V₀ \\sin(\\omega t)",
      meaning: "Mathematical representation of harmonic sinusoidal AC quantities.",
      variables: "I₀ = Peak current (A), V₀ = Peak voltage (V), ω = Angular frequency (rad/s), t = Time (s), φ = Initial phase (rad)",
      unit: "Current in Amperes (A), Voltage in Volts (V)",
      whenToUse: "To calculate instantaneous magnitude or phase at any specified time instant t.",
      calculationExample: {
        problem: "An AC voltage is given by v = 200√2 sin(100πt) Volts. Find peak voltage, frequency, and instantaneous voltage at t = 1/600 s.",
        stepByStep: [
          "Comparing with v = V₀ sin(ωt):",
          "Peak Voltage V₀ = 200√2 V ≈ 282.8 V.",
          "Angular frequency ω = 100π rad/s ==> Frequency f = ω/(2π) = 100π / 2π = 50 Hz.",
          "At t = 1/600 s: v = 200√2 sin(100π × 1/600) = 200√2 sin(π/6) = 200√2 × (1/2) = 100√2 V ≈ 141.4 V."
        ],
        answer: "V₀ = 282.8 V, f = 50 Hz, v(1/600 s) = 141.4 V"
      }
    },
    {
      title: "RMS (Effective) Value of Sinusoidal AC",
      formula: "I_{\\text{rms}} = \\frac{I₀}{\\sqrt{2}} \\approx 0.707 I₀, \\quad V_{\\text{rms}} = \\frac{V₀}{\\sqrt{2}} \\approx 0.707 V₀",
      meaning: "Direct current equivalent for heating dissipation in a resistor over one cycle.",
      variables: "I_rms = RMS current (A), I₀ = Peak current (A), V_rms = RMS voltage (V), V₀ = Peak voltage (V)",
      unit: "Amperes (A) / Volts (V)",
      whenToUse: "Whenever AC meter readings, power dissipation, or household electrical ratings are specified.",
      calculationExample: {
        problem: "A domestic AC line is rated at 220 V, 50 Hz. Calculate the peak voltage and peak-to-peak voltage swing.",
        stepByStep: [
          "Rated voltage V_rms = 220 V.",
          "Peak voltage V₀ = V_rms × √2 = 220 × 1.414 = 311.13 V.",
          "Peak-to-peak voltage = 2V₀ = 2 × 311.13 = 622.26 V."
        ],
        answer: "V₀ = 311.13 V, V_p-p = 622.26 V"
      }
    },
    {
      title: "Average (Mean) Value over Half-Cycle",
      formula: "I_{\\text{avg}} = \\frac{2I₀}{\\pi} \\approx 0.637 I₀, \\quad V_{\\text{avg}} = \\frac{2V₀}{\\pi} \\approx 0.637 V₀",
      meaning: "Charge-transfer equivalent DC value over a single positive half-period.",
      variables: "I_avg = Average current (A), I₀ = Peak current (A)",
      unit: "Amperes (A)",
      whenToUse: "For half-wave integration or moving-coil DC meter readings over a rectified half-cycle.",
      calculationExample: {
        problem: "If the peak value of alternating current is 10 A, find its average value over half a cycle and full cycle.",
        stepByStep: [
          "Half-cycle average: I_avg = (2/π) I₀ = (2/3.1416) × 10 = 6.37 A.",
          "Full-cycle average: I_full = 0 A (symmetrical positive and negative halves)."
        ],
        answer: "Half-cycle = 6.37 A, Full-cycle = 0 A"
      }
    },
    {
      title: "Inductive Reactance",
      formula: "X_L = \\omega L = 2\\pi f L",
      meaning: "Opposition offered by an ideal inductor to alternating current.",
      variables: "X_L = Inductive reactance (Ω), ω = Angular frequency (rad/s), f = Frequency (Hz), L = Self-inductance (H)",
      unit: "Ohms (Ω)",
      whenToUse: "To calculate current limit or voltage drop across an inductor in AC.",
      calculationExample: {
        problem: "An inductor of inductance 50 mH is connected to a 220 V, 50 Hz AC supply. Find its inductive reactance and RMS current.",
        stepByStep: [
          "L = 50 × 10⁻³ H, f = 50 Hz, V_rms = 220 V.",
          "X_L = 2πfL = 2 × 3.1416 × 50 × (50 × 10⁻³) = 15.71 Ω.",
          "I_rms = V_rms / X_L = 220 / 15.71 = 14.0 A."
        ],
        answer: "X_L = 15.71 Ω, I_rms = 14.0 A"
      }
    },
    {
      title: "Capacitive Reactance",
      formula: "X_C = \\frac{1}{\\omega C} = \\frac{1}{2\\pi f C}",
      meaning: "Opposition offered by an ideal capacitor to alternating current.",
      variables: "X_C = Capacitive reactance (Ω), C = Capacitance (F), f = Frequency (Hz)",
      unit: "Ohms (Ω)",
      whenToUse: "To calculate capacitive current limit or filtering impedance in AC circuits.",
      calculationExample: {
        problem: "A 10 μF capacitor is connected to a 110 V, 60 Hz AC source. Find the capacitive reactance and RMS current.",
        stepByStep: [
          "C = 10 × 10⁻⁶ F, f = 60 Hz, V_rms = 110 V.",
          "X_C = 1 / (2πfC) = 1 / (2 × 3.1416 × 60 × 10 × 10⁻⁶) = 1 / (3.77 × 10⁻³) ≈ 265.26 Ω.",
          "I_rms = V_rms / X_C = 110 / 265.26 ≈ 0.415 A."
        ],
        answer: "X_C = 265.26 Ω, I_rms = 0.415 A"
      }
    }
  ],

  neetImportantPoints: [
    "AC ammeters and voltmeters work on the heating effect (Joule's law H ∝ I²) using hot wires, so they measure RMS values and their scales are non-linear (calibrated for quadratic I²).",
    "A standard moving-coil DC meter connected across AC reads exactly 0 because the average torque over 20 ms is zero.",
    "Inductive reactance X_L is directly proportional to frequency (X_L ∝ f). For DC (f = 0), an ideal inductor acts as a short circuit (0 Ω).",
    "Capacitive reactance X_C is inversely proportional to frequency (X_C ∝ 1/f). For DC (f = 0), an ideal capacitor acts as an open circuit (∞ Ω).",
    "Form Factor = RMS / Average = (I₀/√2) / (2I₀/π) = π/(2√2) ≈ 1.11.",
    "Peak Factor = Peak / RMS = I₀ / (I₀/√2) = √2 ≈ 1.414."
  ],

  commonConfusions: [
    {
      commonConfusion: "Believing that average AC current over a full cycle produces heat in a resistor equal to zero.",
      correctFact: "Heat produced is proportional to i²(t) which is ALWAYS positive at all instants. The net heat is H = I_rms² R t > 0, even though net charge transferred is zero.",
      whyItMattersForNEET: "Frequent conceptual trap in NEET Assertion-Reason questions."
    },
    {
      commonConfusion: "Assuming that 220 V AC and 220 V DC have the same peak electrical shock hazard.",
      correctFact: "220 V AC has a peak voltage of 220√2 ≈ 311 V, giving a peak-to-peak shock of 622 V, making AC significantly more lethal than 220 V DC.",
      whyItMattersForNEET: "Tested directly in statement-based questions on household electricity."
    },
    {
      commonConfusion: "Thinking that in a capacitor, voltage leads current because charge accumulates first.",
      correctFact: "Current (flow of charge) MUST occur first to deposit charge on the plates before a voltage can develop. Hence, Current leads Voltage by 90°.",
      whyItMattersForNEET: "Core phase concept tested in almost every NEET AC paper."
    },
    {
      commonConfusion: "Confusing Resistance (R) with Reactance (X_L or X_C).",
      correctFact: "Resistance irreversibly dissipates electrical energy as heat (P = I_rms² R). Reactance stores energy temporarily in magnetic or electric fields and returns it without net power loss.",
      whyItMattersForNEET: "Fundamental distinction required for understanding Wattless current and power factor."
    }
  ],

  quickRevision: [
    "Sinusoidal AC: i = I₀ sin(ωt), v = V₀ sin(ωt), ω = 2πf = 2π/T.",
    "Full-cycle Average = 0; Half-cycle Average = 2I₀/π ≈ 0.637 I₀.",
    "RMS Value: I_rms = I₀/√2 ≈ 0.707 I₀, V_rms = V₀/√2 ≈ 0.707 V₀.",
    "Pure Resistor: v and i in phase (φ = 0°), I_rms = V_rms / R, P = V_rms I_rms.",
    "Pure Inductor: Current lags Voltage by 90° (φ = +90°), X_L = 2πfL, Average Power = 0.",
    "Pure Capacitor: Current leads Voltage by 90° (φ = -90°), X_C = 1/(2πfC), Average Power = 0.",
    "DC limits: Inductor offers 0 Ω (short circuit); Capacitor offers ∞ Ω (open circuit)."
  ],

  pyqs: [
    {
      id: "pyq-ac-2021",
      year: 2021,
      exam: "NEET UG",
      question: "An inductor of inductance L, a capacitor of capacitance C and a resistor of resistance R are connected in series to an AC source of potential difference V volts as shown. The potential differences across L, C and R are 40 V, 10 V and 40 V, respectively. The amplitude of the current flowing through LCR series circuit is 10√2 A. The impedance of the circuit is:",
      options: [
        "4 Ω",
        "5 Ω",
        "4√2 Ω",
        "5√2 Ω"
      ],
      correctAnswer: 1,
      explanation: "Step 1: Calculate the resultant net RMS voltage across the series LCR circuit: V_rms = √[V_R² + (V_L - V_C)²] = √[40² + (40 - 10)²] = √[40² + 30²] = √[1600 + 900] = √2500 = 50 V.\nStep 2: Amplitude (peak value) of current is given as I₀ = 10√2 A. The RMS current is I_rms = I₀ / √2 = (10√2) / √2 = 10 A.\nStep 3: Impedance of the circuit Z = V_rms / I_rms = 50 V / 10 A = 5 Ω. (Option B is correct).",
      conceptTested: "RMS voltage vector addition in LCR and impedance formula Z = V_rms / I_rms.",
      difficulty: "Medium"
    },
    {
      id: "pyq-ac-2015",
      year: 2015,
      exam: "AIPMT",
      question: "A resistance 'R' draws power 'P' when connected to an AC source. If an inductance is now placed in series with the resistance, such that the impedance of the circuit becomes 'Z', the power drawn will be:",
      options: [
        "P (R/Z)²",
        "P √(R/Z)",
        "P (R/Z)",
        "P"
      ],
      correctAnswer: 0,
      explanation: "Step 1: Initial circuit has only resistance R: Power P = V_rms² / R.\nStep 2: When inductance L is added in series, the impedance becomes Z. The new RMS current is I'_rms = V_rms / Z.\nStep 3: The new power dissipated in the resistor is P' = I'_rms² R = (V_rms / Z)² R = (V_rms² / R) · (R² / Z²) = P (R/Z)². Thus, Option A is correct.",
      conceptTested: "Power dissipation variation with impedance and power factor.",
      difficulty: "Medium"
    },
    {
      id: "pyq-ac-2011",
      year: 2011,
      exam: "AIPMT",
      question: "In an AC circuit an alternating voltage e = 200√2 sin(100t) volts is connected to a capacitor of capacity 1 μF. The RMS value of the current in the circuit is:",
      options: [
        "10 mA",
        "100 mA",
        "20 mA",
        "200 mA"
      ],
      correctAnswer: 2,
      explanation: "Step 1: From the voltage equation e = 200√2 sin(100t): V₀ = 200√2 V, so V_rms = V₀ / √2 = 200 V, and angular frequency ω = 100 rad/s.\nStep 2: Capacitive reactance X_C = 1 / (ωC) = 1 / (100 × 10⁻⁶) = 10⁴ Ω = 10,000 Ω.\nStep 3: RMS current I_rms = V_rms / X_C = 200 / 10,000 = 0.02 A = 20 mA. Option C is correct.",
      conceptTested: "Capacitive reactance and RMS current calculation.",
      difficulty: "Easy"
    }
  ],

  practiceQuestions: [
    {
      id: "prac-ac-1",
      question: "If an alternating current is expressed as i = 6 sin(100πt) + 8 cos(100πt) A, the RMS value of the current is:",
      options: [
        "10 A",
        "5√2 A",
        "7 A",
        "14 A"
      ],
      correctAnswer: 1,
      explanation: "The current is a superposition of two orthogonal sinusoidal waves: i(t) = 6 sin(ωt) + 8 cos(ωt). The resultant peak amplitude is I₀ = √(6² + 8²) = √(36 + 64) = √100 = 10 A. The RMS current is I_rms = I₀ / √2 = 10 / √2 = 5√2 A.",
      conceptTested: "Superposition of AC waves and resultant RMS value.",
      difficulty: "Medium"
    },
    {
      id: "prac-ac-2",
      question: "A capacitor blocks DC because for direct current (f = 0):",
      options: [
        "Capacitance becomes zero",
        "Capacitive reactance becomes zero",
        "Capacitive reactance becomes infinite",
        "Dielectric breaks down"
      ],
      correctAnswer: 2,
      explanation: "Capacitive reactance is X_C = 1 / (2πfC). For DC, f = 0, so X_C = 1/0 = ∞. The capacitor acts as an infinite resistance, blocking steady DC current completely.",
      conceptTested: "DC behavior of capacitors.",
      difficulty: "Easy"
    }
  ]
};
