// 20 High-Yield Original NEET UG 2026 MCQs for Electromagnetic Waves Self-Test

export interface McqQuestion {
  id: number;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export const emSelfTestQuestions: McqQuestion[] = [
  {
    id: 1,
    question: "During the charging of a parallel plate capacitor, the displacement current between the plates is equal to:",
    options: [
      "Zero because the gap is an insulator",
      "The conduction current in the connecting wires",
      "Half of the conduction current in the connecting wires",
      "Double the conduction current in the connecting wires"
    ],
    correctIndex: 1,
    explanation: "By Maxwell's generalised Ampère-Maxwell law, total current across any closed boundary is continuous: I_conduction (in wire) = I_displacement (across dielectric gap)."
  },
  {
    id: 2,
    question: "Which of the following Maxwell's equations represents the non-existence of isolated magnetic monopoles?",
    options: [
      "∮ E · dA = Q_enclosed / ε₀",
      "∮ B · dA = 0",
      "∮ E · dl = -dΦ_B / dt",
      "∮ B · dl = μ₀(I_c + ε₀ dΦ_E / dt)"
    ],
    correctIndex: 1,
    explanation: "Gauss's law for Magnetism (∮ B · dA = 0) states that the net magnetic flux through any closed surface is zero, confirming magnetic field lines form continuous closed loops and isolated monopoles do not exist."
  },
  {
    id: 3,
    question: "An electromagnetic wave is travelling in a vacuum along the +y direction. If its electric field oscillates along the +z direction, what is the direction of the magnetic field?",
    options: [
      "+x direction",
      "-x direction",
      "+z direction",
      "-y direction"
    ],
    correctIndex: 0,
    explanation: "Wave velocity direction v̂ = Ê × B̂. Here v̂ = +ĵ and Ê = +k̂. We need k̂ × B̂ = +ĵ. Using unit vector products, k̂ × (+î) = +ĵ. Hence B is along the +x direction (+î)."
  },
  {
    id: 4,
    question: "If the amplitude of the electric field in a plane EM wave is E₀ = 600 V/m, the amplitude of the magnetic field B₀ is:",
    options: [
      "2 × 10⁻⁶ T",
      "1.8 × 10¹¹ T",
      "2 × 10⁶ T",
      "600 T"
    ],
    correctIndex: 0,
    explanation: "B₀ = E₀ / c = 600 / (3.0 × 10⁸) = 2.0 × 10⁻⁶ T = 2 μT."
  },
  {
    id: 5,
    question: "The ratio of energy stored in the electric field to the energy stored in the magnetic field in an electromagnetic wave travelling through vacuum is:",
    options: [
      "c : 1",
      "1 : c",
      "1 : 1",
      "c² : 1"
    ],
    correctIndex: 2,
    explanation: "In an electromagnetic wave, energy is equally divided between electric and magnetic fields: ⟨u_E⟩ = ⟨u_B⟩ = ¼ ε₀ E₀², giving a ratio of 1 : 1."
  },
  {
    id: 6,
    question: "Which of the following electromagnetic waves has the highest penetrating power and shortest wavelength?",
    options: [
      "Ultraviolet rays",
      "X-rays",
      "Gamma rays",
      "Microwaves"
    ],
    correctIndex: 2,
    explanation: "Gamma rays have the highest frequency (f > 10¹⁹ Hz), shortest wavelength (λ < 10⁻¹² m), and maximum photon energy, giving them the highest penetrating power."
  },
  {
    id: 7,
    question: "The correct sequence of EM waves in order of INCREASING frequency is:",
    options: [
      "Radio waves < Microwaves < Infrared < Visible < Ultraviolet < X-rays < Gamma rays",
      "Gamma rays < X-rays < Ultraviolet < Visible < Infrared < Microwaves < Radio waves",
      "Radio waves < Infrared < Microwaves < Visible < Ultraviolet < Gamma rays < X-rays",
      "Microwaves < Radio waves < Infrared < Visible < Ultraviolet < X-rays < Gamma rays"
    ],
    correctIndex: 0,
    explanation: "Frequency increases in the sequence: Radio waves < Microwaves < Infrared < Visible light < Ultraviolet < X-rays < Gamma rays."
  },
  {
    id: 8,
    question: "Microwaves are generated by which of the following devices?",
    options: [
      "Coolidge tube",
      "Klystron and Magnetron valves",
      "Radioactive nuclear decay",
      "Carbon arc lamp"
    ],
    correctIndex: 1,
    explanation: "Microwaves are produced by special vacuum tubes like Klystrons, Magnetrons, and Gunn diodes."
  },
  {
    id: 9,
    question: "The stratospheric ozone layer is vital for life on Earth because it absorbs harmful:",
    options: [
      "Infrared radiation",
      "Ultraviolet radiation",
      "Radio waves",
      "Microwaves"
    ],
    correctIndex: 1,
    explanation: "The ozone layer (O₃) absorbs solar UV radiation (especially UV-B and UV-C with λ < 300 nm), preventing severe skin cancer and cellular DNA damage."
  },
  {
    id: 10,
    question: "In a non-magnetic medium with dielectric constant ε_r = 9.0 and μ_r = 1.0, the speed of an electromagnetic wave is:",
    options: [
      "3.0 × 10⁸ m/s",
      "1.0 × 10⁸ m/s",
      "9.0 × 10⁸ m/s",
      "0.33 × 10⁸ m/s"
    ],
    correctIndex: 1,
    explanation: "v = c / √(μ_r ε_r) = (3.0 × 10⁸) / √9 = (3.0 × 10⁸) / 3 = 1.0 × 10⁸ m/s."
  },
  {
    id: 11,
    question: "A beam of electromagnetic radiation of energy U is completely absorbed by a surface. The momentum transferred to the surface is:",
    options: [
      "U / c",
      "2U / c",
      "U / c²",
      "Zero"
    ],
    correctIndex: 0,
    explanation: "For complete absorption, Δp = U / c. (For complete reflection, momentum transfer is doubled to 2U / c)."
  },
  {
    id: 12,
    question: "Which of the following optical phenomena conclusively proves the TRANSVERSE nature of light waves?",
    options: [
      "Interference",
      "Diffraction",
      "Refraction",
      "Polarisation"
    ],
    correctIndex: 3,
    explanation: "Polarisation can only occur in transverse waves where oscillations are perpendicular to the propagation vector. Longitudinal waves cannot be polarised."
  },
  {
    id: 13,
    question: "Infrared radiation is often referred to as 'heat waves' primarily because:",
    options: [
      "It has the highest photon energy in the spectrum",
      "Water molecules and other polar compounds readily absorb IR radiation, increasing their thermal motion",
      "It produces ionisation in air molecules",
      "It is emitted only by the human body"
    ],
    correctIndex: 1,
    explanation: "Infrared waves resonate with the natural vibrational frequencies of water and molecular bonds in organic materials, directly transferring energy into thermal kinetic energy."
  },
  {
    id: 14,
    question: "An electromagnetic wave with frequency f = 3 × 10¹⁴ Hz belongs to which region of the spectrum?",
    options: [
      "Ultraviolet",
      "Visible",
      "Infrared",
      "Microwave"
    ],
    correctIndex: 2,
    explanation: "Wavelength λ = c / f = (3 × 10⁸) / (3 × 10¹⁴) = 10⁻⁶ m = 1000 nm = 1 μm. This lies in the Infrared region (700 nm to 1 mm)."
  },
  {
    id: 15,
    question: "Which electromagnetic wave is widely used in LASIK eye surgery for precise corneal reshaping?",
    options: [
      "Infrared rays",
      "Ultraviolet laser (Excimer laser)",
      "Microwaves",
      "Gamma rays"
    ],
    correctIndex: 1,
    explanation: "Ultraviolet light emitted by excimer lasers (λ ~ 193 nm) allows microscopic photoablation without causing thermal damage to adjacent delicate corneal tissues."
  },
  {
    id: 16,
    question: "When an electromagnetic wave travels from air into glass, which of the following quantities remains completely UNCHANGED?",
    options: [
      "Wavelength",
      "Speed",
      "Frequency",
      "Wave vector k"
    ],
    correctIndex: 2,
    explanation: "Frequency is an intrinsic property determined solely by the oscillating source and never changes across media. Speed and wavelength decrease in denser media."
  },
  {
    id: 17,
    question: "The dimensions of 1 / √(μ₀ ε₀) are identical to the dimensions of:",
    options: [
      "Acceleration",
      "Force",
      "Velocity",
      "Energy"
    ],
    correctIndex: 2,
    explanation: "c = 1 / √(μ₀ ε₀). Its dimensions are [L T⁻¹] (Velocity of light in vacuum)."
  },
  {
    id: 18,
    question: "The radiation pressure exerted by an EM wave of intensity I on a completely reflecting surface at normal incidence is:",
    options: [
      "I / c",
      "2I / c",
      "I / c²",
      "I · c"
    ],
    correctIndex: 1,
    explanation: "On a 100% reflecting surface, momentum transfer is doubled due to reflection: Radiation pressure P_rad = 2I / c."
  },
  {
    id: 19,
    question: "Greenhouse effect on Earth is primarily caused by the trapping of which type of radiation by atmospheric greenhouse gases?",
    options: [
      "Solar ultraviolet rays",
      "Terrestrial infrared rays",
      "Cosmic rays",
      "Solar visible light"
    ],
    correctIndex: 1,
    explanation: "Earth absorbs short-wavelength solar visible light and re-emits long-wavelength terrestrial Infrared radiation, which is strongly absorbed by atmospheric CO₂ and H₂O."
  },
  {
    id: 20,
    question: "An alternating voltage V = V₀ sin(ωt) is applied across a parallel plate capacitor. The displacement current I_d is proportional to:",
    options: [
      "sin(ωt)",
      "cos(ωt)",
      "sin²(ωt)",
      "Zero at all times"
    ],
    correctIndex: 1,
    explanation: "I_d = C (dV/dt) = C · d/dt [V₀ sin(ωt)] = C V₀ ω cos(ωt). Thus, displacement current leads the voltage by a phase of 90° (π/2 rad) and is proportional to cos(ωt)."
  }
];
